### ISSUE TITLE
Auto Expand video details

### ISSUE THREAD

**Issue by Gabarito007** [ParticleCore/Iridium#205] opened 2017-10-04 22:01 UTC
Hi.

Youtube+ (plus) had a variable that auto expand video description named:
VID_LAYT_AUTO_PNL

Is it possible to allow that same feature to Iridium?

Thx

**Comment by ParticleCore** [comment] 2017-10-04 22:02
Duplicate of https://github.com/ParticleCore/Iridium/issues/163

**Closed by ParticleCore** 2017-10-04 22:02 UTC
Labels: duplicate

**Comment by Gabarito007** [comment] 2017-10-04 22:06
Oh, my!
My filter settings was to display just open issues.
I see now.

Thank you.

**Comment by Gabarito007** [comment] 2017-10-04 22:19
Sorry to bother again, but I couldn't find that feature.
I found just show/hide/remove comments, but not description.

**Comment by ParticleCore** [comment] 2017-10-04 22:22
The feature is not implemented. Please read the instructions before opening an issue:


>#### Feature requests:
> - There is currently no intention to accept feature requests, but they can be requested nonetheless for future consideration
> - Feature requests will be automatically closed and labeled as "Feature" for easier access and better organization
> - If a feature request is considered to be implemented it will be re-opened for the duration of the implementation

https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by Gabarito007** [comment] 2017-10-04 22:24
Sorry and thanks.
:)
