### ISSUE TITLE
Broken settings page (youtube.com/iridium-settings)

### ISSUE THREAD

**Issue by 07416** [ParticleCore/Iridium#120] opened 2017-08-30 12:41 UTC
The settings page has always appeared in this form:

![2017-08-30 17_02_24-iridium](https://user-images.githubusercontent.com/14923168/29876322-1802faf6-8da5-11e7-8fa6-e9609fe38c19.png)

I've tried reinstalling Iridium and I don't have Flash player installed. The issue persists with all addons  (with the exception of userscript manager Greasemonkey) and userscripts disabled. No [web console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) output and I've cleared everything in about:preferences#privacy > "Clear history when Firefox closes" (cookies, cache, history etc.).

- Firefox 55.0.3 (64-bit)
- Windows 10 64-bit
- Iridium 0.1.9b 
- Greasemonkey 3.11

**Comment by ParticleCore** [comment] 2017-08-30 13:57
You likely have a browser setting that is breaking the layout or something else, the settings page appears correctly with no problems on my end.

Also you are not using the latest version of Iridium since some of the settings available in v0.1.9b aren't even displayed on your screenshot (Enable quick controls, for example).

Screenshot of the same settings page on FF 55.0.3 x64 + Greasemonkey 3.11


![ss](https://user-images.githubusercontent.com/9222661/29875992-11a31660-8d8b-11e7-9b1b-7f1faa7d60ba.png)



Please follow the instructions as requested, all the steps: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by 07416** [comment] 2017-08-30 14:04
@ParticleCore I was using an older screenshot, I've now updated the image. I'm using the latest version of Iridium.

**Comment by ParticleCore** [comment] 2017-08-30 14:05
Follow the linked instructions as requested.

**Comment by MattSturgeon** [comment] 2017-09-01 04:54
Also can't reproduce. @07416 do you have any custom stylesheets enabled (e.g. using stylus)?

**Comment by 07416** [comment] 2017-09-02 16:56
@MattSturgeon No, I have no "user style" enabled. I've disabled all addons with the exception of Greasemonkey. 
I will reset Firefox as soon as possible.

**Comment by ParticleCore** [comment] 2017-09-04 07:48
I will close this for now, if you still have this problem follow the instructions as requested.

**Closed by ParticleCore** 2017-09-04 07:48 UTC
Labels: invalid

**Comment by 07416** [comment] 2017-09-04 18:10
@ParticleCore I will comment once I have refreshed Firefox.
Are you interested in knowing what exactly causes this issue? Should I save my broken Firefox installation?

**Comment by ParticleCore** [comment] 2017-09-04 18:11
It might be helpful to know the cause for others that might have the same problem, but you are not obligated to do anything like that.

**Comment by 07416** [comment] 2017-11-30 15:56
The problem fixed itself, apparently at the time of Firefox 57 release (I still haven't moved to a fresh profile).
