### ISSUE TITLE
Timestamp links refreshing the page

### ISSUE THREAD

**Issue by Mike-Correa** [ParticleCore/Iridium#96] opened 2017-08-02 16:35 UTC
Clicking on a timestamp link (from the comment session or from the video description) causes the whole page to reload. It also should not scroll up to the top of the screen if the mini player is enabled. This happens on Chrome.

**Comment by ParticleCore** [comment] 2017-08-02 18:44
Duplicate of #14

**Closed by ParticleCore** 2017-08-02 18:44 UTC
Labels: duplicate
