### ISSUE TITLE
[Feature Request] Only one player/video playing

### ISSUE THREAD

**Issue by kilara1988** [ParticleCore/Iridium#401] opened 2018-03-25 15:38 UTC
YouTube Center script and an addon called: Enhancer for YouTube™ have a very nice feature that i really liked.At all times only one video/player is playing at once.
For example if you start a video and go browsing on other tabs and find another video and you want to play the new video, if you click to play the new video the other video stops and only the new one plays.If you then go back to the first video and play it the other one stops.Basically only the last video that you start playing is playing and all others stop. If you have lots of tabs open this is very nice since i don't have to go back and find the tab of the video that is currently playing, pause it and then go back to the new video tab and start it.

**Comment by ParticleCore** [comment] 2018-03-25 15:40
Duplicate of #134

**Closed by ParticleCore** 2018-03-25 15:40 UTC
Labels: duplicate
