### ISSUE TITLE
A Video Stop Button

### ISSUE THREAD

**Issue by muhammadbilal0x00** [ParticleCore/Iridium#605] opened 2018-11-03 18:29 UTC
A great add-on which provides all needed features. Can you add a Stop button in video player to stop the video at any time to to prevent buffering of long videos like this add-on for old layout. "https://addons.mozilla.org/en-US/firefox/addon/youtube-stop-button/"

**Comment by ParticleCore** [comment] 2018-11-04 00:01
Duplicate of #11

**Closed by ParticleCore** 2018-11-04 00:01 UTC
Labels: duplicate
