### ISSUE TITLE
Weird bug after scrolling up from mini-player

### ISSUE THREAD

**Issue by n-o-o-b** [ParticleCore/Iridium#337] opened 2018-02-08 14:41 UTC
Sometimes, if I scroll down to the comments with the mini-player enabled and then scroll back up to the top, I get this weird effect where the main player takes up only half of the space it should, as you can see in the images below. I don't know what causes it, and most of the time it doesn't happen.

I'm on the current stable Firefox version, and I'm using the add-on version of Iridium, although this also happened with the userscript version when I used it with Violentmonkey. My operating system is Windows 10.

![iridium bug](https://user-images.githubusercontent.com/19697175/35978441-a8387d78-0cdd-11e8-866f-97e553b88c47.png)
![iridium bug 2](https://user-images.githubusercontent.com/19697175/35978444-aa2bff6a-0cdd-11e8-875c-3c83c010efb7.png)

**Comment by ParticleCore** [comment] 2018-02-08 15:23
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by n-o-o-b** [comment] 2018-02-08 15:55
I've followed the instructions. It doesn't happen after a restart. I tried with both just Iridium enabled and with everything else enabled too. However, I did get it when using a new profile with Iridium newly-installed with default settings. I think the issue is to do with accessing videos from an external URL. The first time I accessed the video it was by clicking the YouTube logo from the player on https://genius.com/Gil-scott-heron-whitey-on-the-moon-annotated. When I tried searching for the video through YouTube search on the new profile, the bug didn't happen. And the issue only happened on the first tab that was opened from Genius. When I tried copying the URL and opening it in another tab, the bug didn't happen.

**Comment by tgn-ff** [comment] 2018-02-09 07:11
I think I have STR to reproduce it every time. Browser, script manager and script-vs-extension doesn't seem to matter.

1. Visit https://dot.kde.org/2018/02/06/plasma-512-out-and-it-faster-stabler-and-has-more-features-ever.
2. **Left**-click on the video title, or let the video play and **left**-click the YouTube logo. Middle-click and right-click > Open in New Tab won't make it reproduce.
3. Let the video play in the new tab that opened in step 3.
4. Scroll down until the mini player appears, then scroll to the top.

**Comment by ParticleCore** [comment] 2018-02-09 09:03
@tgn-ff Got it, finally! I'm able to reproduce it now, will see what I can do to fix this, but I have a feeling that this one might be unfixable if the browser itself is delaying the execution of Iridium in favor of a faster page opening.

**Comment by ParticleCore** [comment] 2018-02-09 09:05
@tgn-ff Can you reproduce this problem in Chrome too?

**Comment by BlueNinja0** [comment] 2018-02-09 22:43
I think this is a duplicate of #307

**Comment by Daisenki** [comment] 2018-02-10 07:02
Confirm that bug on Firefox 58.0.2 with Iridium Addon 0.0.5

**Closed** 2018-02-10 14:09 UTC
Labels: bug
