### ISSUE TITLE
[Feature] Request -  Fit to page max width (Cinema/Theater Mode)

### ISSUE THREAD

**Issue by JamesHage** [ParticleCore/Iridium#511] opened 2018-07-19 20:12 UTC
Youtube Center allowed for a maximum page width to be specified when in cinema/theater mode, allowing "you to limit the maximum width the player is allowed to reach". 

Having control over the player size while still full screen in the browser is an absolute blessing and one of my favorite features. Thank you for writing the definitively best Youtube addon!

**Comment by ParticleCore** [comment] 2018-07-20 16:15
Duplicate of #418

**Closed by ParticleCore** 2018-07-20 16:15 UTC
Labels: duplicate
