### ISSUE TITLE
Iridium stop working under Greasemonkey 4.0

### ISSUE THREAD

**Issue by tgp1994** [ParticleCore/Iridium#240] opened 2017-11-20 19:09 UTC
Ever since I updated to Firefox 57 (which necessitated updating to Greasemonkey 4.0), Iridium will now randomly stop working for Youtube. It's icon will no longer be present in the YT UI, and none of the features are functioning. The script still shows up in GM. When I open the source, I see I have version 0.2.9b.

**Comment by ParticleCore** [comment] 2017-11-20 19:36
Duplicate of #235 

Latest Iridium version is 0.3.8b, you are using 0.2.9b

**Closed by ParticleCore** 2017-11-20 19:36 UTC
Labels: duplicate
