### ISSUE TITLE
Add a loop button?

### ISSUE THREAD

**Issue by CNSabata** [ParticleCore/Iridium#469] opened 2018-05-28 20:16 UTC
I didn't really have any clue how to like, ask for a feature, I'm guessing it's here.
I think it's a good idea to make Iridium a wide-feature extension, which is why I installed it in the first place. I really like it. The only thing I miss is the loop button from one of my other extensions.
So, yeah. Here you go. If this is considered, that'd be good.
Good day.

**Comment by ParticleCore** [comment] 2018-05-28 20:44
Duplicate of #12

**Closed by ParticleCore** 2018-05-28 20:44 UTC
Labels: duplicate
