### ISSUE TITLE
Restoring Mini Player not functioning

### ISSUE THREAD

**Issue by greenscarf07** [ParticleCore/Iridium#611] opened 2018-11-07 10:34 UTC
Browser Name: Chrome

  Browser Version: Version 70.0.3538.77

  Operating System: Windows 10

  Software Type: Chrome extension

  Software Version: 0.2.4

  Problem Description: when searching - or moving to another page - mini player loses the ability to restore video and also when attempting to close the video the video's audio stills play 

  Steps to reproduce: 
- playing a video
- type in to youtube search bar
- click enter
- search results show up and video is still playing in corner
- click "restore" button and nothing happens
- click "cross" and video audio still plays even though video has gone from the screen

  Additional details: here is a screen recording of me reproducing the issue: https://streamable.com/52bnj

**Comment by ParticleCore** [comment] 2018-11-07 12:00
Duplicate of #575

**Closed by ParticleCore** 2018-11-07 12:00 UTC
Labels: duplicate
