### ISSUE TITLE
Feature: Split "Autoplay Video" into "Autoplay Video" and "Autoplay Playlist"

### ISSUE THREAD

**Issue by AlexBlandin** [ParticleCore/Iridium#527] opened 2018-07-31 20:32 UTC
Whilst the ability to enable or disable autoplay is useful, especially if you have multiple tabs open, that you cannot have disable autoplay but still have autoplaying playlists (such as for music), or vice versa, is a missed opportunity right now.

**Comment by ParticleCore** [comment] 2018-07-31 20:37
Duplicate of #78

**Closed by ParticleCore** 2018-07-31 20:37 UTC
