### ISSUE TITLE
Add a hide video button on thumbnails, similar to the pop-up player button

### ISSUE THREAD

**Issue by brigcam** [ParticleCore/Iridium#289] opened 2018-01-18 21:50 UTC
Hi, I've just seen the pop-up player button after updating to the latest version, that's cool! I was wondering if it would be possible to also have a "hide" button on thumbnails in the subscriptions page, it'd be faster rather than opening the drop-down menu and choosing the hide video option.

I ask this because I always hide videos on my subscription page after having watched them, and it gets tedious if there are many of them (i.e. if I want to delete a serie of videogame trailers I've already seen).

Thank you!

**Comment by ParticleCore** [comment] 2018-01-18 23:09
I'm going to link this request with a very similar one since both could eventually be made as a drop down choice for the same feature.

Duplicate of #233

**Closed by ParticleCore** 2018-01-18 23:09 UTC
Labels: duplicate
