### ISSUE TITLE
Show volume overlay when adjusted

### ISSUE THREAD

**Issue by strafe** [ParticleCore/Iridium#538] opened 2018-08-10 22:36 UTC
This goes hand-in-hand with #537, when adjusting the volume some kind of overlay would be displayed showing the current volume. I think since Iridium provides the ability to manually step the volume rather than dragging a slider around it makes sense to show the exact volume value.

**Comment by ParticleCore** [comment] 2018-08-11 15:40
Duplicate of #45

**Closed by ParticleCore** 2018-08-11 15:40 UTC
Labels: duplicate
