### ISSUE TITLE
Play Videos Automatically

### ISSUE THREAD

**Issue by muhammadbilal0x00** [ParticleCore/Iridium#604] opened 2018-11-03 18:20 UTC
Hello dear, i m using this add-on since long time and it is one of my favorites. I usually keep disable "Play videos automatically" but suddenly it stop working and videos start to play automatically on opening YouTube video page but after that it works on next videos in current tab.

**Comment by LyesSaadi** [comment] 2018-11-03 18:36
See #600 !

**Comment by ParticleCore** [comment] 2018-11-04 00:00
Duplicate of #600

**Closed by ParticleCore** 2018-11-04 00:00 UTC
Labels: duplicate
