### ISSUE TITLE
No tooltip is displayed on sidebar videos

### ISSUE THREAD

**Issue by DerpMcDerp** [ParticleCore/Iridium#389] opened 2018-03-14 22:02 UTC
The firefox browser disables tooltips for the title attribute if you have this:

```css
/* Iridium.css: */
a.yt-simple-endpoint span { pointer-events: none }
```

Which causes no tooltip to appear for `<span title="some long video title">` when you hover on any video thumbnail in the sidebar.

**Comment by ParticleCore** [comment] 2018-03-14 22:18
Duplicate of https://github.com/ParticleCore/Iridium/issues/388

**Closed by ParticleCore** 2018-03-14 22:18 UTC
Labels: duplicate
