### ISSUE TITLE
YT videos freeze after 1 minute 50 seconds

### ISSUE THREAD

**Issue by BondiBear** [ParticleCore/Iridium#632] opened 2018-11-19 21:30 UTC
This started 2 days ago on Firefox. Tried clearing cache and cookies, but no help there.
Not all, but most videos freeze and stop loading after 1:50. Only reloading the tab resolves the issue.

Version 0.2.4 / FF63.0.3.

**Comment by ParticleCore** [comment] 2018-11-20 04:35
Please follow the instructions as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by BondiBear** [comment] 2018-11-20 11:39
Browser Name: FF

  Browser Version: 63.0.3

  Operating System: Windows 10

  Software Type: Iridium addon

  Software Version: 0.2.4 

  Problem Description: YT videos freeze after 1 minute 50 seconds. This started 2 days ago on Firefox. Tried clearing cache and cookies, but no help there. Not all, but most videos freeze and stop loading after 1:50. Only reloading the tab resolves the issue.

  Steps to reproduce: example video: https://youtu.be/rQ70ngH0GKQ. For me this freezes  after 1 minute 50 seconds, but only on first load. Reloading the tab restars this video at 0:00 and run through until the end.

**Comment by ParticleCore** [comment] 2018-11-20 19:12
I can't make it happen with me under the same setup. Did you follow all the troubleshooting steps as requested?

**Comment by Basjohn** [comment] 2018-11-23 07:56
Almost exact same issue for 3 weeks now, although at 1:05 for me.

Browser Name: FireFox

Browser Version: 63.0.3 (64-bit)

Operating System: Windows 10

Software Type: Iridium script

Software Version: 0.2.4

Problem Description: YT videos freeze after 1 minute 05 seconds. Not all videos, it largely seems random. Can be fixed by reloading the video and starting playback from after the 1:05 breakpoint

Steps to reproduce: Unsure. Problem appears random. Sometimes a video in a tab I've left for a while, sometimes a video from the college at the end of another video. Happens about 7/10 times I watch anything.

**Comment by ParticleCore** [comment] 2018-11-23 08:04
Did anyone follow the troubleshooting steps as requested?

**Comment by Basjohn** [comment] 2018-11-23 08:38
> 
> 
> Did anyone follow the troubleshooting steps as requested?

I did. No changes.

**Comment by ParticleCore** [comment] 2018-11-23 08:39
Did you test to see if the same problem happened without Iridium running? Because I have yet to find this happening to me and if I cannot replicate it I cannot find what is causing it and I cannot fix it as a result.

**Comment by Basjohn** [comment] 2018-11-23 08:41
I'll try that. YT is horrendous without Iridium though, like wading through video feces in fishnet stockings.

**Comment by ParticleCore** [comment] 2018-11-23 08:50
I understand that but you did say that you followed the troubleshooting steps and that was one of them:

> - Disable the extension and restart the browser.

If people reporting the issues don't actually follow the troubleshooting steps as requested then it becomes a waste of time for everyone because I will ask for them either way otherwise I am unable to help out when I am not also having the issue myself.

**Comment by Basjohn** [comment] 2018-11-23 09:17
Because running WITHOUT it is the last possible step. It's like me saying a boat is leaky and someone else saying "Did you try not using a boat at all? Did you get wet then?" Well yes, I got rather wet without the boat.

But silly semantics should be ignored, this is troubleshooting thread after all.

The problem does not occur without Iridium. The problem persists with Iridium even through different OS installs. I understand you have trouble reproducing it, as I do. Thus far it feels random. I believe the next best step would be if me or the other user could try and narrow down reproduction of the issue somehow. I will keep a close watch on variables around it occurring.

**Comment by Nazta** [comment] 2018-11-23 14:11
On my computer it crashes the playback after 1min 19 sec.  It also wont play back video about half the time when you click on the next button next to the play button. Just crashes the playback stating it can't recognize any formats.

It seems to be an issue with something done in the version 0.2.3 and/or 0.2.4, both issues are fixed by disabling those versions, or downgrading to 0.2.2 version for functionality and fewer bugs.

**Comment by eduzappa18** [comment] 2018-11-24 06:39
**Browser Name:** Firefox
**Browser Version:** 63.0.3 (64-bit)
**Operating System:** Windows 10
**Software Type:** Userscript
**Userscript Manager:** Tampermonkey 4.8.5847
**Userscript Version:** 0.2.4

**Steps to reproduce:** Play a video till the end, then click any of the "Up next" recommended videos in the same tab. That next video will stop buffering within the first 2 minutes and will stay frozen with the loading animation.
When opening a video in a new tab the video will play normally.

**Additional details**: tested in a new firefox profile, only tampermonkey and iridium installed with default settings.
the issue occurs only when iridium is running. it works normally when iridium is disabled.

**Comment by ParticleCore** [comment] 2018-11-24 11:13
I am not able to replicate this problem which means that this is very likely a change on YouTube that I haven't received yet, in which case it should be a matter of time until it starts happening to me.

**Comment by Nazta** [comment] 2018-11-26 12:59
I'm starting to suspect it's a combination. Since downgrading versions fixes the problem

**Comment by ParticleCore** [comment] 2018-11-27 19:52
It's definitely some new YouTube update that I have yet to receive because I have been and still am playing videos every day and this problem hasn't manifested once on my end.

**Comment by JLJTGR** [comment] 2018-11-28 01:49
**Browser Name:** Firefox
**Browser Version:** 63.0.3
**Operating System:** Windows 10 x64 1809
**Software Type:** Addon
**Software Version:** 0.2.4

It's been happening to me for about a couple weeks at most and I thought I would share my observations of when it occurs and what I found to circumvent it.

Like eduzappa18 mentioned, it happens to me when I click another video from a finished video.  IE, that 4x3 grid of thumbnails that appears in the video space.  If I click a video from the YouTube homepage or channel listing, it will work fine.

After navigating to the new video, immediately refreshing the page will avoid the issue just as though it were a link from the homepage, etc.

The video location where it will freeze seems a tiny bit random to me.  Sometimes it's around ~30s in, sometimes ~60s in.  The stats for nerds overlay just shows that eventually the buffer health stops maintaining a buffer and it decays to zero and freezes playback.  No waiting amount will cause it to recover.

Specific settings in Iridium are required for me to see this issue occur.  Different "Play videos automatically" and "Default video quality" combinations can cause it to manifest or not... or so I thought.  Testing it just now, turning off "Play videos automatically" will cause it to happen.  (As long as you come from another video as described above)  A week ago, I thought that a specific and fixed video quality would also cause it to freeze, but I can't reproduce that now.  

I think the most likely way for it to get stuck is: to not play automatically, prevent auto resolution, and choose a video through the 4x3 grid and not any normal link.

**Comment by ParticleCore** [comment] 2018-11-28 12:52
Good news, it's finally happening to me, I'll try to find out what is causing it and push a fix as soon as I can.

**Comment by indeedwatson** [comment] 2019-06-15 20:06
Is this still an issue?

**Comment by ParticleCore** [comment] 2019-10-06 22:23
This should be fixed in version 1.0.0

**Closed by ParticleCore** 2019-10-06 22:23 UTC
Labels: bug, fixed
