### ISSUE TITLE
This page slows down Firefox...

### ISSUE THREAD

**Issue by Qoolize** [ParticleCore/Iridium#992] opened 2024-08-20 21:05 UTC
Hello! Today I saw that Iridium has been further developed and I updated it today. After a short time I noticed that Iridium was causing Firefox to freeze and Firefox was giving me a message that the site was slowing down Firefox.
The old version 0.2.5 (yes... I haven't updated it in a long time) works.

If you need more information, please write.

**Comment by ParticleCore** [comment] 2024-08-20 21:14
Issue might be related to #977 can you confirm if the issue is still happening when you're logged out?

**Comment by Qoolize** [comment] 2024-08-21 08:48
Hi!
No, the problem goes away when I'm logged out. The problem description matches the one in 977.

**Comment by ParticleCore** [comment] 2024-08-21 14:06
Thank you, I'll mark this one as duplicate of #977 and follow up with the fix in the original case.

**Closed by ParticleCore** 2024-08-21 14:06 UTC
Labels: bug, duplicate
