### ISSUE TITLE
"Restore" button in the mini-player is broken?

### ISSUE THREAD

**Issue by Lythed** [ParticleCore/Iridium#607] opened 2018-11-04 21:01 UTC
Hi, some time ago, the "Pop-out" button was broken (fixed in the latest update) but i think, the Restore button are broken too, seem to be the same for the progress bar. (see attachement)
EDIT: The "Close" button close the video but not the audio.
If anyone can confirm that. :)

![untitled](https://user-images.githubusercontent.com/35495389/47969653-2a4ba580-e07b-11e8-917b-a492129b8eea.png)

Iridium 0.2.4 (Greasemonkey)
Firefox 63.0.1 (64-bit)

**Comment by ParticleCore** [comment] 2018-11-04 23:09
Duplicate of #575

**Closed by ParticleCore** 2018-11-04 23:09 UTC
Labels: duplicate
