### ISSUE TITLE
AMO Description Screenshot

### ISSUE THREAD

**Issue by Riajyuu** [ParticleCore/Iridium#568] opened 2018-09-21 14:30 UTC
![image](https://user-images.githubusercontent.com/16912240/45887256-cad75600-bdaa-11e8-84e3-0dd142b2baeb.png)

Excuse me ??????????????????????

**Comment by ParticleCore** [comment] 2018-09-21 14:43
Duplicate of #463

**Closed by ParticleCore** 2018-09-21 14:43 UTC
Labels: duplicate
