### ISSUE TITLE
[Feature] Improvements to Mouse Wheel Volume Adjustment

### ISSUE THREAD

**Issue by Pwnulatr** [ParticleCore/Iridium#457] opened 2018-05-19 06:37 UTC
~~[Magic Actions](https://addons.mozilla.org/en-US/firefox/addon/magic-actions-for-youtube/) and [Enhancer For YouTube](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/) both have the ability to adjust the video volume with mouse wheel scrolling, but the first neither are open source and the first one is Malware essentially, so it would be nice to see this implemented.~~ I don't recall which one or if it is both of them which allow you to set the interval of volume per "click' on the mouse wheel turning with an On Screen Display of the current volume while it is being adjusted.

**Comment by rEnr3n** [comment] 2018-05-19 06:45
It's in the video settings. Enable it. Although it doesn't have option to set volume interval. No on-screen display either.

**Comment by Pwnulatr** [comment] 2018-05-19 06:50
Perhaps I should adjust my issue to only include the improvements made to the already existing volume adjustment.

**Comment by ParticleCore** [comment] 2018-05-19 11:42
Duplicate of #45

**Closed by ParticleCore** 2018-05-19 11:42 UTC
Labels: duplicate
