### ISSUE TITLE
Support for youtube classic

### ISSUE THREAD

**Issue by killoid** [ParticleCore/Iridium#514] opened 2018-07-26 16:51 UTC
is it possible to support this [addon](https://github.com/thisdotvoid/youtube-classic-extension)? i am using it mainly for [this](https://twitter.com/cpeterso/status/1021626510296285185) reason.

**Comment by PoorPocketsMcNewHold** [comment] 2018-07-26 17:04
[Already talked about here.](https://github.com/ParticleCore/Iridium/issues/513)

**Comment by PoorPocketsMcNewHold** [comment] 2018-07-26 17:12
[Already talked about here.](https://github.com/ParticleCore/Iridium/issues/513) If you do want support for the old interface, [Use the old script](https://github.com/ParticleCore/Particle).

**Comment by Eisys** [comment] 2018-07-26 17:50
I've tried switching over to the new layout and hate it more every time I try. Been using 1.9.6 Youtube+ for all this time and haven't noticed any bugs so it's fine to use. It also has more features.

**Comment by ParticleCore** [comment] 2018-07-26 20:00
Duplicate of #513

**Closed by ParticleCore** 2018-07-26 20:00 UTC
Labels: duplicate
