### ISSUE TITLE
Video pauses when entering/exiting full-screen mode

### ISSUE THREAD

**Issue by gigoose** [ParticleCore/Iridium#594] opened 2018-10-24 06:42 UTC
Browser Name: Google Chrome

  Browser Version: 70.0.3538.67

  Operating System: Windows 10 build 1803

  Software Type: Extension

  Software Version: 0.2.2

  Problem Description: When using the "scroll for details" feature of YouTube which allows scrolling down for comments, etc. when in full-screen mode in conjunction with the Iridium "Play videos automatically" setting turned off, videos will pause when entering/exiting full-screen mode.

  Steps to reproduce: 

1. Start with a fresh google chrome install
2. Make sure the "scroll for details" feature on YouTube is turned on (go to youtube.com, open developer's tools (ctrl-shift-i), go to console tab and enter `document.cookie="VISITOR_INFO1_LIVE=1jCNAz66qLo"` then refresh browser)
3. Install Iridium extension and make sure the "Play videos automatically" setting is turned off (should be by default).
4. YouTube videos now pause when entering/exiting full-screen mode

  Additional details: 

The "scroll for details" feature is relatively new and has been rolling out to some users.[ Reddit thread about the feature](https://www.reddit.com/r/youtube/comments/9hdmw2/youtube_is_testing_an_awesome_fullscreen_feature/)

**Comment by ariefpizzuti** [comment] 2018-11-13 11:58
Yup youtube just push this new feature to me.

**Comment by Lindt8** [comment] 2018-11-13 19:12
Just to chime in, I just got the "feature" pushed to me as well and am now experiencing this issue too.  Interestingly, as noted by ariefpizzuti, this issue is only present for the "Default view" and not for "Theater mode."

**Comment by ParticleCore** [comment] 2018-11-14 20:01
Finally got it to happen to me, will try to find out a solution for this as soon as I can.

**Comment by ariefpizzuti** [comment] 2018-11-16 10:58
Seems youtube remove the words "scroll for details" when going fullscreen now and no longer pause a video while going fullscreen from the default mode.

**Comment by Katjubu** [comment] 2018-12-05 18:14
I updated to Chrome version 71.0.3578.80 and this problem seems to be fixed. I'm not sure if it was a result of this or if Youtube made some behind the scene changes.

**Comment by Lindt8** [comment] 2018-12-05 21:40
I believe it was a Chrome issue.  The newest update had not been pushed to me yet today, and I was still experiencing the issue.  I manually updated Chrome immediately after testing, and now the issue is completely gone!

**Comment by ParticleCore** [comment] 2018-12-07 19:09
I haven't updated my browser yet but that would explain why I haven't been able to get it to happen on Firefox all this time.

**Comment by godzfire** [comment] 2018-12-10 23:55
Definitely a Chrome issue, can confirm 100% as I was dealing with the same issue. Just manually updated to v71, hoping that will fix the issue.

**Comment by ParticleCore** [comment] 2018-12-10 23:58
Alright, thanks everyone for the help. I'll close this for now since it is related to a browser issue and not the extension.

**Closed by ParticleCore** 2018-12-10 23:58 UTC
Labels: chrome bug
