### ISSUE TITLE
Advanced autoplay controls

### ISSUE THREAD

**Issue by Kaedin** [ParticleCore/Iridium#475] opened 2018-06-11 04:49 UTC
Hi Developer,

Most of the YouTube extensions are lacking a feature to customize autoplay in a more advanced way. Would it be possible to consider implementing these additional controls:

 - Enable/disable "Up next" autoplay =>This setting would prevent browser from loading the displayed "up next" video, stopping at the end screen of the current video

 - Enable/disable "Playlist" autoplay => This setting would prevent browser from loading the next video on the playlist, stopping at the end screen of the current video

With these settings, it would be possible to enable currently available setting "Play videos automatically" to play video in opened window automatically but prevent it from advancing to other videos without permission.

Thanks in advance!

Best regards,
Kaedin

**Comment by snakecase** [comment] 2018-06-11 11:47
Kudos for 1. No sure about 2. What I would like to have is disabling autoplay but having a switch to ignore this setting in playlists.

**Comment by ParticleCore** [comment] 2018-06-11 19:18
Duplicate of #138

**Closed by ParticleCore** 2018-06-11 19:18 UTC
Labels: duplicate
