### ISSUE TITLE
No video playback once Iridium is enabled

### ISSUE THREAD

**Issue by mrzed** [ParticleCore/Iridium#718] opened 2019-05-24 16:53 UTC
Once Iridium as installed all YouTube videos stopped playing - only the spinning chasing line are displayed on a black background. I disabled ALL other extensions without any change. Once Iridium was disabled, all videos started playing back again. I have tested this with the same results in Chrome and Firefox. I have enabled and disabled each setting in Iridium without a change to the issue.

Firefox 67.0
Chrome 74.0.3729.169
Windows 10 Enterprise

I love the blacklisting portion of this extension, so I hope to find resolution for this soon. Thanks!

**Comment by ganego** [comment] 2019-05-24 18:27
We know. Has been discussed to death.
Enable autoplay.  
And close the ticket.

**Comment by AlexFundorin** [comment] 2019-05-31 17:30
No only autoplay, but also endless spinning circle on the black background. Doesn't happen with a script.

**Comment by ParticleCore** [comment] 2019-06-21 12:42
Duplicate of #671

**Closed by ParticleCore** 2019-06-21 12:42 UTC
Labels: duplicate
