### ISSUE TITLE
Youtube community polls not loading voting options.

### ISSUE THREAD

**Issue by JoshS-dev** [ParticleCore/Iridium#964] opened 2024-03-16 01:00 UTC
I'm noticing some youtube polls not loading their options, when clicking on them from the front page at least. Sometimes they are broken and without a 'Vote now' button, but sometimes the options don't load with one. I would share one but this bug I am having a lot of trouble duplicating, one I was about to send inexplicably starting working again - but I have to assume, with this being the only extension I have that affects how youtube works, that this is the one causing it.

I can attempt to share some that have at least one point glitched out:

https://www.youtube.com/channel/UCFbtcTaMFnOAP0pFO1L8hVw/community?lb=UgkxqgzH-3NeFwQJdBHs7tMsK1Cgd1acbZWn
![image](https://github.com/ParticleCore/Iridium/assets/34352316/abfff719-29a5-4bdc-8727-3e880d3da548)

https://www.youtube.com/channel/UCIRGrckNJFQ3CUlwCOQEkPQ/community?lb=UgkxGUghImlAYzfy2AnQQ0ktm5Nj1c1EgW3M
![image](https://github.com/ParticleCore/Iridium/assets/34352316/19a61c78-6682-4f83-ba9a-640c5beb3af3)

https://www.youtube.com/channel/UCTTfeKDGCqxot-KfjHptP_Q/community?lb=UgkxSeppLWPjus6SyiPjgTr6vz8cRovv8n03
![image](https://github.com/ParticleCore/Iridium/assets/34352316/09499cc6-f213-48f5-9382-fd08805a9515)

(Don't question the polls, YouTube recommends me weird polls from people I don't watch lol)

This has started happening in the past day - perhaps even today I cannot fully remember this happening yesterday. It's a strange bug because that last poll was one that I had seen just the other day. And despite this seeming to happen more on newer posts rather than old - and these do not seem to bug out, at least as much, in the community tabs - this seems to be happening more prevalent than I thought upon testing, like this is happening on almost every poll I try to open right now.

Edit : And yes, this does work in incognito mode (i.e. without extensions)

**Comment by ParticleCore** [comment] 2024-03-16 02:46
Just to confirm, during normal use (not incognito) if the extension is disabled the issue does not happen?

**Comment by ParticleCore** [comment] 2024-03-16 02:56
I was able to get it happening to me by accident:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/af97d552-65bf-41f9-bdba-51828f0322fd)


Something to note: this happened in incognito mode with the extension disabled.

**Comment by ParticleCore** [comment] 2024-03-16 03:06
I am also now able to get it to happen for the other polls you linked

![image](https://github.com/ParticleCore/Iridium/assets/9222661/5fa5c240-232c-4d59-8cd8-50192cabedfe)

![image](https://github.com/ParticleCore/Iridium/assets/9222661/0a03e0a7-0d30-4861-af0f-20612c0ed984)

This is happening with the extension disabled, so it is not being caused by it.

It is just another YouTube bug like the many they have, it might go away on its own, but if you want to force it to go away you can try clearing all YouTube data in your browser and that will cause it to issue new experiments/cookies, hopefully one that no longer has that bug.

But just to confirm, during your scenarios did you get a chance to test if the issue was still happening during normal use with the extension disabled?

**Comment by JoshS-dev** [comment] 2024-03-16 03:16
As said, yes I tried this in incognito. Now I did not do it extensively, I tried one that broke and it worked so I assumed it was all good there. If this is just plain a youtube thing, then its a youtube thing haha. Perhaps I could have tested it a few more times in incognito.

**Comment by ParticleCore** [comment] 2024-03-16 03:18
No that is not what I am asking, did you try in normal mode (not incognito) with the extension disabled to see if the issue still keeps happening? Using incongnito mode would change experiments/cookies, so the issue could appear like it went away as a result of the extension being disabled, but that's just misleading, which is why I asked the other scenario; normal mode with the extension disabled.

**Comment by ParticleCore** [comment] 2024-03-16 03:19
I ask this because as you can see, the issue is happening to me with the extension disabled, so it cannot be caused by it, but by YouTube itself. If you disable the extension while in normal browsing mode (not in incognito) the issue should still keep happening because it is not being caused by the extension.

**Comment by JoshS-dev** [comment] 2024-03-16 03:21
Oh sorry, yeah I misunderstood. I wish I could help but I genuinely cant even get this bug to happen normally WITH the extension on, things seem to inexplicably work again so me testing without the extension probably wont say much but yeah its not happening with it on either. Plus if it is doing this for you thats enough for me to know that this isnt on the extension; cant know that kinda thing until I ask someone else to try it out I suppose

**Comment by ParticleCore** [comment] 2024-03-16 03:23
Definitely odd, I know, I did see it sometimes happening (the poll options not showing) and a few seconds later without doing anything on that same page (not reloading, not clicking, nothing at all) the poll options would suddenly show up, but most times they don't.

I'll close this for now as this is not a YT bug, but will keep an eye out for it. If you want to, you can try clearing your YT browsing data (you will have to login again) and it should help get a different config without the bug for you. On my main account the issue has yet to happen again, but on incognito, after a few reloads, it eventually happened.

**Closed** 2024-03-16 15:52 UTC
Labels: youtube bug
