### ISSUE TITLE
Feature Request: Floating Widget Size Control

### ISSUE THREAD

**Issue by SurajDonthi** [ParticleCore/Iridium#299] opened 2018-01-27 18:04 UTC
Hi, Can you please provide the option for the Floating Widget Size as in the old Youtube+ Userscript in the settings.

It would be really helpful.

The current size of the floating widget is too small.

Thank you.

**Comment by ParticleCore** [comment] 2018-01-27 19:10
Duplicate of https://github.com/ParticleCore/Iridium/issues/237

**Closed by ParticleCore** 2018-01-27 19:10 UTC
Labels: duplicate

**Comment by theorist-complex** [comment] 2018-01-31 10:39
Glad I saw this, as I was about to post the same feature request. lol

This is one of the only features that has held me back from switching over to the new version on my 2 pc's that are connected to televisions. The [Floating Player Width](https://github.com/ParticleCore/Particle/wiki/Features#floating-player-width) option makes it super easy to peruse the comment section while still being able to see the video large enough on my HDTVs. Hope to see it implemented sometime soon.

Thanks for all you do, btw - one of the best browser userscript/extensions ever!

**Comment by ParticleCore** [comment] 2018-01-31 11:22
@theorist-complex If you'd follow the linked issue you would see that I do plan to implement it, but the priority for now is on developing the extension versions (and possible bugs that might arise until that time) before thinking on adding more features/improvements.

**Comment by theorist-complex** [comment] 2018-01-31 13:14
I saw it. I was simply commenting about what a useful feature it is and that I hope to see it implemented sometime soon. I wasn't trying to pressure you into making it a priority or anything. If you interpreted the comment that way, that was not my intention.
