### ISSUE TITLE
Beta not working in FF57

### ISSUE THREAD

**Issue by jkluch** [ParticleCore/Iridium#200] opened 2017-09-30 16:59 UTC
I checked the alpha branch and that shows the icon in the top right but no icons below the video to actually use.  I tried the most recent two beta releases, f8030c133db598707bcddb5d855b22664747eb46, 564af7c88b2a019ab229fd3b09b8db505b5f601f and those don't show anything and throw an error in console.

![btlz3mq](https://user-images.githubusercontent.com/514150/31047791-f8f95a72-a5de-11e7-882f-06b6c3ae643f.png)

`Error running script: Iridium
ReferenceError: r is not defined
r is not defined watch:1:7414
	u https://www.youtube.com/watch:1:7414
	Injected https://www.youtube.com/watch:1:8273
	i https://www.youtube.com/watch:1:8317
	o/< https://www.youtube.com/watch:1:9002
	r https://www.youtube.com/watch:5594:84
	<anonymous> https://www.youtube.com/watch:1:84
	<anonymous> https://www.youtube.com/watch:1:2
	r https://www.youtube.com/watch:1:8407
	r https://www.youtube.com/watch:1:8466
	n https://www.youtube.com/watch:1:6694
	e https://www.youtube.com/watch:1:6759
	o https://www.youtube.com/watch:1:7266
	LoadScripts https://www.youtube.com/watch:1:7608
	i https://www.youtube.com/watch:1:8317
	o/< https://www.youtube.com/watch:1:9002
`

**Comment by ParticleCore** [comment] 2017-09-30 17:07
I am currently using it on FF57 with Tampermonkey because Greasemonkey is broken on 57. Follow the instructions as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by jkluch** [comment] 2017-09-30 18:35
Browser Name: Firefox
  Browser Version: 57.0b3 (64-bit)
  Operating System: Windows 10
  Software Type: Userscript
  Software Version: (The version of the Iridium extension you are using; 0.0.1, 0.2.5, etc.)
  Userscript Manager: Violentmonkey
  Userscript Manager Version: 0.3.1b
  Problem Description: problem is described above
  Steps to reproduce: Go to any youtube page with a video

I was unaware that Tampermonkey existed for Firefox, thought it was chrome only.  I tried that and it worked.  I was using Violentmonkey, which was the first thing I found when searching for a FF57 compatible userscript extention.  Particle does work with Violentmonkey which is why I expected Iridium to also work.  I guess this could be marked closed since it's working with Tampermonkey

**Comment by ParticleCore** [comment] 2017-09-30 18:38
Not only that, there are problems with Violentmonkey itself and FF75: https://github.com/violentmonkey/violentmonkey/issues/170

Glad to hear it is working correctly now.

Also this makes this issue a duplicate of https://github.com/ParticleCore/Iridium/issues/101

**Closed by ParticleCore** 2017-09-30 18:38 UTC
Labels: duplicate
