### ISSUE TITLE
Pop-up button on subscriptions page not working.

### ISSUE THREAD

**Issue by Togamgurga** [ParticleCore/Iridium#376] opened 2018-03-01 11:14 UTC
Browser Name: Firefox

  Browser Version: 58.0.2

  Operating System: Windows 10

  Software Type: Extension

  Software Version: 0.0.9

  Problem Description: The pop-up window button on thumnails while on the subscription page has stopped doing anything when clicking it. On the video page the pop-up button works fine. I've disabled all other extensions in case an update to one of them broke something, and I've uninstalled & reinstalled Iridium too, but to no avail. 

  Additional details: It was working fine on Monday, but yesterday it just stopped. The PC wasn't restarted between when it was working and when it stopped. All other Iridium features seem to be unafected. Restarting my pc didn't help. Creating a new profile with only Iridium didn't help, either. Youtube material layout is being used.

**Comment by Tigoreetur** [comment] 2018-03-01 12:00
Same here to.
Browser Name: Chrome
Browser Version: 64.0.3282.186
Operating System: Windows 10 64bit
Software Type: extension
Software Version: 0.0.9

**Comment by ParticleCore** [comment] 2018-03-01 12:33
Duplicate of #374

**Closed by ParticleCore** 2018-03-01 12:33 UTC
