### ISSUE TITLE
Volume features and YouTube Gaming support

### ISSUE THREAD

**Issue by drv42** [ParticleCore/Iridium#410] opened 2018-03-30 10:51 UTC
1) Keep the volume slider expanded at all times.
2) Quick switch to YoutubeGaming interface.
3) Wide screen on YoutubeGaming interface by default.
4) Change volume using the mouse wheel on YoutubeGaming interface.

**Comment by ParticleCore** [comment] 2018-03-30 10:56
Duplicate of #364

**Closed by ParticleCore** 2018-03-30 10:56 UTC
Labels: duplicate
