### ISSUE TITLE
Videos are stuck buffering

### ISSUE THREAD

**Issue by furiifuu** [ParticleCore/Iridium#736] opened 2019-09-11 18:34 UTC
Videos have stopped playing with Iridium enabled recently. Additionally, access to any sort of settings has disappeared.

I am using the latest FIrefox version and have tried all the solutions offered on the internet (as few as they were for this one). Nothing seems to be doing the trick.

Videos will not play, not matter the combination of add-ons I have in addition to Iridium. Once it's disabled, everything works normally.

Additionally, the options normally displayed under the video have lost all functionality. 

OS: Windows 8.1 64 bit
Firefox ver.: Quantum - 69.0 (64-bit)

Is anyone else experiencing this?

Regards.

**Comment by ParticleCore** [comment] 2019-10-06 21:53
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0

**Comment by ParticleCore** [comment] 2019-10-06 21:55
Sorry, closed wrong issue

**Comment by ParticleCore** [comment] 2019-10-06 21:55
Can you update to version 1.0.0 and let me know if you are still having this issue?

**Comment by ParticleCore** [comment] 2019-10-06 21:59
Actually there's a lot of duplicates of this one.
Duplicate of #671

**Closed by ParticleCore** 2019-10-06 21:59 UTC
Labels: bug
