### ISSUE TITLE
Closing the mini-player does not stop the video

### ISSUE THREAD

**Issue by StephanBussmann** [ParticleCore/Iridium#608] opened 2018-11-05 20:36 UTC
Hey there,
I have the strange behaviour when I navigate to other sites while the video is still playing and I close the mini-player, the video does not stop.
I can still hear the sound and need to refresh the site.
It started a few weeks ago.

**Comment by ParticleCore** [comment] 2018-11-05 20:39
Duplicate of #575

**Closed by ParticleCore** 2018-11-05 20:39 UTC
Labels: duplicate
