### ISSUE TITLE
Add Options

### ISSUE THREAD

**Issue by Fannste94** [ParticleCore/Iridium#588] opened 2018-10-14 13:30 UTC
Hello I want to ask you can you please add an option in the Iridium extension to block the Related YouTube search result videos and also add an option to remove the Autoplay up next option

![41231](https://user-images.githubusercontent.com/44136509/46917316-ffaf8500-cfc5-11e8-9687-3292270facd0.jpg)

![412313212](https://user-images.githubusercontent.com/44136509/46917319-03430c00-cfc6-11e8-82bd-ae274bfe8cec.jpg)

**Comment by ParticleCore** [comment] 2018-10-14 13:31
Duplicate of #138

**Closed by ParticleCore** 2018-10-14 13:31 UTC
Labels: duplicate
