### ISSUE TITLE
Video can be moved around when "Video always stays visible" is enabled

### ISSUE THREAD

**Issue by BitGrub** [ParticleCore/Iridium#127] opened 2017-09-01 00:27 UTC
![2017-09-01](https://user-images.githubusercontent.com/20694416/29950565-792b3252-8eb4-11e7-97b8-8f0a8116b8c5.png)
#minor #bugs #lol

**Comment by ParticleCore** [comment] 2017-09-01 00:34
Duplicate of https://github.com/ParticleCore/Iridium/issues/125

If you don't want bugs then don't use an unstable userscript that is still in beta phase.
I am sure there are better options that don't have any bugs for you to enjoy if all you can do is feedback sarcasm.

**Closed by ParticleCore** 2017-09-01 00:34 UTC
Labels: duplicate

**Comment by BitGrub** [comment] 2017-09-01 00:57
Alright no need to get all bitter about it. I was just using the issue tracker as intended.

If you don't like other people reporting bugs in code you're still working on, don't use Github lmao

**Comment by ParticleCore** [comment] 2017-09-01 20:00
@BitGrub I apologize, it has been a stressful couple of months, there are no hard feelings intended on my part with the harsh replies, even though it might sound like it.
