### ISSUE TITLE
Autoplay Not Working

### ISSUE THREAD

**Issue by on1no** [ParticleCore/Iridium#636] opened 2018-11-29 18:13 UTC
Hi
And Sorry For My Bad English

My issue is with AutoPlay 

Iridium Working Great with youtube..

So Every Time i Need To watch an Adult Content NSFW Videos i Must Login To My Youtube Account..

But i Dont Like to Login to My youtube Account

So i Use this Script.. YouTube Age Bypass (no reload required)
https://greasyfork.org/en/scripts/373678-youtube-age-bypass-no-reload-required

So i can watch Any NSFW Video without Need to login in to my youtube Account

But Your Script Iridium Autoplay button Not Working With YouTube Age Bypass Script

See Here
"Warning NSFW Thumbnail"

Your Iridium Script With login to my Account For NSFW Videos and Autoplay button Working Great
https://i.imgur.com/WxYPSis.jpg

Your Iridium Script Without login to my Account And using YouTube Age Bypass For NSFW Videos and the Autoplay button Not Working 
https://i.imgur.com/s0bhTY4.png

The Youtube Video Link "Warning NSFW"
youtube.com/watch?v=xCFAK8xruF8

And Thank you

**Comment by ParticleCore** [comment] 2018-11-29 21:43
Duplicate of #377

**Closed by ParticleCore** 2018-11-29 21:43 UTC
Labels: duplicate
