### ISSUE TITLE
Video keeps playing when changing pages option - not working correctly.

### ISSUE THREAD

**Issue by shonay** [ParticleCore/Iridium#610] opened 2018-11-07 09:51 UTC
Hi there,
I'm not sure if you're aware of this, just wanted to write to let you know.
I have enabled the "Video keeps playing when changes pages option" - this allows for the small player on the bottom right, however if i click on the X to close that window - the video closes but the audio continues to play afterwards. It used to close the video completely before - not sure if this is a bug or a feature that you amended - hence wanted to find out.

Thanks.

**Comment by ParticleCore** [comment] 2018-11-07 12:00
Duplicate of #575

**Closed by ParticleCore** 2018-11-07 12:00 UTC
Labels: duplicate
