### ISSUE TITLE
[Bug] Recommended tab disappears if the first video is added to the blacklist .

### ISSUE THREAD

**Issue by Tigoreetur** [ParticleCore/Iridium#372] opened 2018-02-27 13:12 UTC
If you add a channel to the blacklist from the recommended tab the recommended tab disappears 

Browser Name: Chrome
Browser Version: 64.0.3282.186
Operating System: Windows 10 64bit
Software Type: extension
Software Version: 0.0.9

https://youtu.be/U11YRxD3zhk

**Comment by Tigoreetur** [comment] 2018-02-27 13:28
It happens on Firefox to.

Browser Name: Firefox
Browser Version: 58.0.2
Operating System: Windows 10 64bit
Software Type: extension
Software Version: 0.0.9

**Comment by ParticleCore** [comment] 2018-03-18 14:33
I am unable to reproduce this problem, please follow the troubleshooting steps as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by ParticleCore** [comment] 2018-03-24 09:29
Closing this for now, follow the instructions in my previous reply if you are still have this issue.

**Closed by ParticleCore** 2018-03-24 09:29 UTC
