### ISSUE TITLE
Iridium not working at all

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#872] opened 2021-01-07 07:27 UTC
software details:
````
manifestVersion: 1.2.7
cookieEnabled: true
doNotTrack: unspecified
language: tr-TR
buildID: 20201220193140
name: Firefox
vendor: Mozilla
version: 85.0
arch: x86-64
os: linux (ubuntu)
````

steps to recreate the problem: add-on not working at all  ![resim](https://user-images.githubusercontent.com/5833034/103863965-d57c9d00-50d2-11eb-9847-771ceeb6f53e.png)

**Comment by Osahashi** [comment] 2021-01-31 17:34
I really don't understand why are you posting this? We all know that and no, nothing will be fixed. Why are you not reading the pinned message? 
Why are people still use Iridium??? It's completely broken since a long time and even now there are many "topXX"-lists who recommend Iridium in 2021... 
Iridium is dead and the developer has abandoned it. I wish someone would remove it from the add-on store that we all can forget it.

**Comment by ImmortalFishy** [comment] 2021-02-23 01:06
> I really don't understand why are you posting this? We all know that and no, nothing will be fixed. Why are you not reading the pinned message?

If you read the pinned message only the AMO version is the one that won't be updated, the version here on Github is still updated when the developer finds time. Here's a segment of the pinned message to clarify:

>If the add-on on the AMO store does not receive any more updates that means they insist on being unreasonable and I will no longer tolerate that.

>The unlisted version is exactly the same, is updated and also receives updates faster. If you wish to continue receiving updates you can find the most recent version here: https://github.com/ParticleCore/Iridium/wiki/Download

That being said, I can confirm I'm having the same issue with Iridium 1.2.7, on Windows 10 20H2 and Firefox 86.0, the Youtube home page works fine but individual video pages fail to load anything more than the background color.

**Comment by Andromeda-K22** [comment] 2021-02-23 02:10
Verifying this issue on my end as well; Firefox 85.0, Windows 10.

**Comment by Deerath** [comment] 2021-02-23 02:13
Also verifying that it is preventing videos from loading. When I disable it, videos load. Firefox 85.0.2, Windows 10

**Comment by NekoAlosama** [comment] 2021-02-24 03:53
@ParticleCore

**Closed** 2023-12-07 14:57 UTC
Labels: wontfix
