### ISSUE TITLE
Iridium doesn't allow Firefox to release media memory as it is measured in about:memory

### ISSUE THREAD

**Issue by tgn-ff** [ParticleCore/Iridium#228] opened 2017-11-05 17:39 UTC
Browser Name: Firefox
Browser Version: 56.0.2 (and 58.0a1)
Operating System: GNU/Linux
Software Type: Userscript
Software Version: 0.3.5b
Userscript Manager: Tampermonkey (and Violentmonkey)
Userscript Version: 4.5.5570 (2.8.17)
Problem Description: See title and "steps to reproduce" for more details.

**Steps to reproduce:**

1) Create a new profile, install a script manager and then install the Iridium script.

2) Disable Iridium and restart Firefox.

3) Open `about:memory`.

4) Take a measurement and search (`Ctrl+F`) for the term "media". It shouldn't appear at this point.

5) Open a random page that doesn't contain any media, and a youtube video page **in the same content process**. [You'll need that (the bold) in order to prevent the termination of the process when you'll close the youtube video tab. The `about:performance` or hovering over the tab in Nightly will give you the PID of the process in which the tab is running.]

6) Measure the memory while the video is playing. Search for "media" and now you should find a result consuming memory in that content process.

7) Close the video tab and click the buttons to free memory: GC, CC and Minimize memory usage.

8) Measure the memory again and search for "media". [*There are no results with Iridium disabled.*]

9) Enable Iridium in the script manager, restart Firefox and repeat steps 3 to 8. With Iridium enabled, "media" still appears to consume memory.

Additional details: Practically, I've seen that playing ~5 videos (3-5min, 24-30fps and 720-1080p) in the same tab (which also means the same content process), results in about 100MiB more memory, for content process alone, with Iridium enabled than disabled.

**Comment by ParticleCore** [comment] 2017-11-05 18:08
I can confirm the same, but I don't know if it is something I am going to be able to fix without sacrificing features, such as autoplay control , video ads control, and many others.

**Comment by ParticleCore** [comment] 2017-11-05 19:00
@tgn-ff I believe I have fixed this memory problem, but I have no possibility to test it on Linux, so I would like to ask you if you could test this version on your end to see if the problem is also fixed for your OS:

https://gist.github.com/ParticleCore/83dacf49d54c38630dd4f4c9a59f6841

**Comment by tgn-ff** [comment] 2017-11-05 19:25
Yes, that seems to fix it. I tested Firefox 56.0.2 with legacy GM and Nightly with VM. Thanks!

**Comment by ParticleCore** [comment] 2017-11-05 20:16
Thanks for the quick test, the fix will ship with the next update!

**Comment by ParticleCore** [comment] 2017-11-05 22:25
Looks like the fix is premature, it is causing parts of the YouTube layout to fail to load, will keep checking a better fix for this issue.

**Closed** 2017-11-08 07:24 UTC
Labels: beta, bug
