### ISSUE TITLE
60fps videos stutter (not Iridium's fault)

### ISSUE THREAD

**Issue by SamTheGr8est** [ParticleCore/Iridium#202] opened 2017-10-02 03:37 UTC
Browser Name: Chrome

Browser Version: 61.0.3163.100 

Operating System: Windows 10 Redstone

Software Type: Userscript 

Software Version: 0.3.1b

Userscript Manager: TamperMonkey

Userscript Version: 4.4

Problem Description: 60fps video stutter when VP8/VP9 is used.

Steps to reproduce: 
1. Use hardware acceleration.
2. Load a 720/1080p60fps youtube video on a medium-tier computer.
3. Video will stutter and keep buffering periodically.   

Additional details: This can be negated by forcing youtube to use H.264 instead of VP8/VP9. It's more of a feature, but still a fixable bug.

**Comment by ParticleCore** [comment] 2017-10-02 08:03
Duplicate of https://github.com/ParticleCore/Iridium/issues/161

**Closed by ParticleCore** 2017-10-02 08:03 UTC
Labels: duplicate
