### ISSUE TITLE
Controlling audio with mouse wheel

### ISSUE THREAD

**Issue by Alkaris** [ParticleCore/Iridium#743] opened 2019-09-20 16:36 UTC
Could you make it so you can scroll anywhere on the video for changing the audio volume on videos, instead of just when the mouse is hovering over the audio control of the video, and show an indicator overlay of the volume level percentage.

**Comment by ParticleCore** [comment] 2019-09-20 16:44
Duplicate of #45

**Closed by ParticleCore** 2019-09-20 16:44 UTC
Labels: duplicate
