### ISSUE TITLE
[Feature] hiding Scrollbar

### ISSUE THREAD

**Issue by Tharn** [ParticleCore/Iridium#1001] opened 2024-09-16 20:50 UTC
When Iridium fills the whole browser window, it doesn't actually fill the whole viewport. So if you have a laptop with native 720p, you get 710p and ugly scaling because the scrollbar is still taking up horizontal space. It would be nice if Iridium had an option to make the scrollbar slide-in on top of the video/page the same way the top bar slides in. Or to have it toggle-able.

**Comment by ParticleCore** [comment] 2024-09-16 22:49
Hi, I think I just implemented this in #1000 today, can you take a look at it?

**Comment by Tharn** [comment] 2024-09-16 23:53
Amazing, that's me on AMO as well. Wasn't sure if you read there. Appreciate this very much. I'll check it out.

**Comment by ParticleCore** [comment] 2024-09-17 00:48
The feature will be available on 2.1.2, it is not out yet.

**Comment by ParticleCore** [comment] 2024-09-17 15:45
Closing as duplicate of #1000

**Closed by ParticleCore** 2024-09-17 15:45 UTC
Labels: duplicate
