### ISSUE TITLE
Auto play Options (Feature Request)

### ISSUE THREAD

**Issue by zanezonair** [ParticleCore/Iridium#940] opened 2024-02-23 06:37 UTC
autoplay affects all videos even ones in playlists.

can you add toggles/options to iridium's auto play so it can do the following?:
### auto play the entire playlist (including the first video)

to be more clear. i would like for an option to keep auto play enabled on playlists. but disabled if im not in a playlist.

i used to use some extentions to replicate this. but iridium overrides them sadly so i have to ask for this to be a feature in it.
if this is confusing still i am sorry. i tend to have bad wording. ill galdly try to give clarity on anything i mean.

**Comment by ParticleCore** [comment] 2024-02-23 17:35
Thanks for taking the time to explain it further. I do not think I am willing to implement such a configurable capability for autoplay (it is already hard as it is), but I am planning on adding a toggle button on the video page so the autoplay can be quickly turned on and off without having to go to the options page every time.

This way if you want to turn off autoplay while listening to a play list you can quickly turn it on in the video page itself. Hopefully that would make things for you easier.

As for the incompatibility with the other extensions I would like to see if I can do something to fix that, can you tell me what extension you were using to configure your autoplay experience?

**Comment by ParticleCore** [comment] 2024-02-23 17:38
Just to make it more clear, the feature would show an autoplay button in the video page similar to the old version:
![image](https://github.com/ParticleCore/Iridium/assets/9222661/814518ca-e5ba-4c66-9c9b-f2fbb6ca8613)

**Comment by zanezonair** [comment] 2024-02-23 19:43
> Thanks for taking the time to explain it further. I do not think I am willing to implement such a configurable capability for autoplay (it is already hard as it is), but I am planning on adding a toggle button on the video page so the autoplay can be quickly turned on and off without having to go to the options page every time.
> 
> This way if you want to turn off autoplay while listening to a play list you can quickly turn it on in the video page itself. Hopefully that would make things for you easier.
> 
> As for the incompatibility with the other extensions I would like to see if I can do something to fix that, can you tell me what extension you were using to configure your autoplay experience?

i listen to youtube mixes a lot. and i value immersion. hence why i was asking about all this. heres the extention i use to configure auto play to my liking. iridium overrides its settings sadly as even with it configured to let playlists auto play playlists still wont auto play.

https://chromewebstore.google.com/detail/youtube-no-buffer-stop-au/afgfpcfjdgakemlmlgadojdfnejkpegd

**Comment by ParticleCore** [comment] 2024-02-23 21:48
Thanks for sharing the extension that is having compatibility issues with Iridium.

I am trying to understand what you are expecting to happen here. You would like for that extension to control video autoplay instead of Iridium, right?

In which cause simply enabling autoplay in Iridium should leave the player behavior as default on YouTube, which means your other extension should have total control over the autoplay.

Am I understanding this correctly?

**Comment by ParticleCore** [comment] 2024-02-23 21:49
Thanks for sharing the extension that is having compatibility issues with Iridium.

I am trying to understand what you are expecting to happen here. You would like for that extension to control video autoplay instead of Iridium, right?

In which cause simply enabling autoplay in Iridium should leave the player behavior as default on YouTube, which means your other extension should have total control over the autoplay.

Am I understanding this correctly?

What steps should I follow in order to better understand your issue, and what should I expect to happen but it is not happening?

**Comment by ParticleCore** [comment] 2024-02-23 22:00
Here is what I am testing with Iridium enabled and YouTube No Buffer enabled:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/f9daa0cc-1aad-4b5c-a509-0c09167ebea1)
Video is paused when I open it

![image](https://github.com/ParticleCore/Iridium/assets/9222661/01f92f3c-332c-425e-92d7-571b610f5ea2)
Video is not paused when I open it nor when I navigate to a different video and back again

![image](https://github.com/ParticleCore/Iridium/assets/9222661/5b5cbd92-0bd1-4d28-8777-a2017e9a9281)
Videos in playlist do not play automatically the very first time I open, but then they play automatically when changing videos in playlist

So far I did not find any issues with the autoplay compatibility between Iridium and YouTube No Buffer

Just to be sure, did you test your issue with `autoplay` enabled in Iridium?
![image](https://github.com/ParticleCore/Iridium/assets/9222661/180cfba4-8de2-494a-8a28-da74080a7bdf)

Because if it is not enabled then the autoplay will be intercepted by Iridium all the time as it was designed.

**Closed** 2024-02-24 00:42 UTC
Labels: feature

**Comment by ParticleCore** [comment] 2024-02-24 03:00
@zanezonair I'm so sorry, but did you solve your issue? Was the autoplay not being enabled in iridium that was causing the problem?
