### ISSUE TITLE
User definable increment for mouse wheel volume

### ISSUE THREAD

**Issue by strafe** [ParticleCore/Iridium#537] opened 2018-08-10 22:33 UTC
This is something I'm missing from Magic Actions, I prefer to be able to adjust the volume in increments of 1 rather than 5 and since the number is arbitrary I think it makes sense to make it customisable.

**Comment by ParticleCore** [comment] 2018-08-11 15:41
Duplicate of #471

**Closed by ParticleCore** 2018-08-11 15:41 UTC
Labels: duplicate
