### ISSUE TITLE
Wheres all the settings gone.

### ISSUE THREAD

**Issue by Vantageright** [ParticleCore/Iridium#747] opened 2019-10-08 03:21 UTC
There are 3 options available when accessed from the toolbar icon - Dark theme under General and Play automatically and Force max thumbnail resolution under Player. Download(???), Channels and Blacklist are now all empty. Report a bug works too.
Completely inaccessible from youtube.
If this was done on purpose, you done goofed.
Tried on another profile, completely blank. Same thing.

software details:
````
manifestVersion: 1.0.0
cookieEnabled: true
doNotTrack: 1
language: en-GB
buildID: 20191001234643
name: Firefox
vendor: Mozilla
version: 69.0.2
arch: x86-64
os: win

**Comment by AmethystSpark** [comment] 2019-10-08 04:31
Same thing is happening to me.

**Comment by Santademon** [comment] 2019-10-08 05:32
The new update seems to have nerfed the addon. I've switched back to the old YouTube Plus, for now. Hopefully, the features will be re-added in future updates.

**Comment by ParticleCore** [comment] 2019-10-08 07:35
Duplicate of #745

**Closed by ParticleCore** 2019-10-08 07:35 UTC
Labels: duplicate

**Comment by chrcoluk** [comment] 2020-06-16 20:55
Hi does anyone have the link to the old version for chrome?  The feature comparison is huge, and the new one is barely worth using.
