### ISSUE TITLE
Allow Custom Sizes for Floating Player

### ISSUE THREAD

**Issue by Raeffion** [ParticleCore/Iridium#331] opened 2018-02-06 04:09 UTC
Two options for this that come to mind:
- Allow the user to control the size (in px) via the Iridium settings or on right click of the player.
- Make the floating player resizable with the cursor and remember (similar to moving the floating player). Should this be implemented, a button could be added that remembers the size/position of the floating player when activated.

**Comment by ParticleCore** [comment] 2018-02-06 09:02
Duplicate of #108

**Closed by ParticleCore** 2018-02-06 09:02 UTC
Labels: duplicate
