### ISSUE TITLE
Really big problem

### ISSUE THREAD

**Issue by Hunam6** [ParticleCore/Iridium#788] opened 2019-10-23 17:16 UTC
When Iridium is enabled, youtube pages looks like this :

![image](https://user-images.githubusercontent.com/38606542/67417534-4d8f9d80-f5c9-11e9-8c70-796f97a42748.png)

And when it is disable, it looks normal.

(I have the latest version of Firefox)

**Comment by TrueNevermore** [comment] 2019-10-23 19:11
I was also seeing this earlier, but now I am just getting a "Problem Loading Page" on the latest Firefox Nightly
Youtube loads up fine with the extension disabled
![image](https://user-images.githubusercontent.com/7907925/67426054-45bf0180-f5a7-11e9-9214-f42e96e62c4e.png)

**Comment by Hunam6** [comment] 2019-10-23 19:18
Yes me too I have this problem with playlists

**Comment by ParticleCore** [comment] 2019-10-23 19:24
I need more information than this, browser, version of the browser, extension version, how to recreate, etc. This is not enough for me because it is not happening to me.

**Comment by Hunam6** [comment] 2019-10-23 19:27
I have Firefox Nightly last version (72.0a1), Iridium last version (1.2.4) and you just need to have Iridium enable to have the bug.

**Comment by TrueNevermore** [comment] 2019-10-23 19:32
Same setup here, Firefox Nightly 72.0a1 Iridium 1.2.4 and any time I try to open a youtube page (whether it be the homepage, the following page, a channel page, a video page etc.) it shows me the error page shown in my previous image. Issue persists on a fresh profile with only Iridium installed.

**Comment by ParticleCore** [comment] 2019-10-23 19:45
What are your extension settings so I can try seeing if it might be a combination of them. Also a screenshot of the webpage with Iridium disabled.

**Comment by Hunam6** [comment] 2019-10-23 19:48
On my side, every option is enabled


When it's disabled; everything seems to be normal.

**Comment by TrueNevermore** [comment] 2019-10-23 19:55
Dark Theme Enabled
Quick Controls Enabled
Play Videos Automatically Disabled
Force Max Thumbnail Resolution Enabled
Allow HFR Streams Enabled
Sync Settings Enabled
Show Settings Button In Youtube Enabled
![image](https://user-images.githubusercontent.com/7907925/67429155-8f124f80-f5ad-11e9-9a5c-3ab4c0c32daa.png)

**Comment by ParticleCore** [comment] 2019-10-23 20:04
Thanks for both helping. Still can't make it happen. Can you install previous versions until the problem stops to see when the issue started?

Instructions to install: https://github.com/ParticleCore/Iridium/wiki/Download#how-to-install-add-on-from-github

Previous versions can be downloaded here:

1.2.4 https://github.com/ParticleCore/Iridium/blob/d9cf4cfc0a469fd53f3cdad22a4b47c138ad1568/dist/Iridium.xpi

1.2.3 https://github.com/ParticleCore/Iridium/blob/ac5c06260b8a46d433220157d5e43182f03da206/dist/Iridium.xpi

1.2.2 https://github.com/ParticleCore/Iridium/blob/444dfdec42b2c7613f48d799f18fb6f5de69f811/dist/Iridium.xpi

1.2.1 https://github.com/ParticleCore/Iridium/blob/e938f14bec2e17aca7aedeeefc2f4ae64ff095f2/dist/Iridium.xpi

1.2.0 https://github.com/ParticleCore/Iridium/blob/dc79b9c8444d07f7d86c7162c142b9e0c23a170e/dist/Iridium.xpi

1.1.1 https://github.com/ParticleCore/Iridium/blob/9b69df709668c4728a0ffc7d9badbe61e01c0297/dist/Iridium.xpi

1.1.0 https://github.com/ParticleCore/Iridium/blob/3ce6b6cbefd19d236ec3390fefc4e18ab30cf17c/dist/Iridium.xpi

**Comment by TrueNevermore** [comment] 2019-10-23 20:17
I tried all the versions you linked, all on a fresh profile, and the issue persisted across all of them

**Comment by ParticleCore** [comment] 2019-10-23 20:22
@TrueNevermore that's bad then because that means YouTube changed something and I have to wait to get those changes and see what is breaking. Sorry for this but it's out of my control.

**Comment by ParticleCore** [comment] 2019-10-23 20:51
Got it, it's a Firefox problem, they must've changed something in their API and it's now breaking everything. Gonna see what is going on, but I'm afraid this one is not up to me.

**Comment by ParticleCore** [comment] 2019-10-23 21:19
Tried to find a workaround for this problem like I did in #759, but this time is even worse because it's the API itself that is corrupting the website information.

A bug report has been opened for this problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1590898

**Comment by Hunam6** [comment] 2019-10-23 22:19
Sad..

**Comment by Sukigu** [comment] 2019-10-25 22:21
It has been found that Firefox [bug 1590898](https://bugzilla.mozilla.org/show_bug.cgi?id=1590898) was a regression from [bug 1583700](https://bugzilla.mozilla.org/show_bug.cgi?id=1583700), which, among other things, set pref `browser.tabs.documentchannel` to `true` by default. So while that isn't fixed, a workaround to continue using Iridium on the latest Nightlies is to flip that pref to `false` in `about:config`.

**Comment by wahuka** [comment] 2019-10-26 01:23
![Screenshot_2019-10-26 YouTube](https://user-images.githubusercontent.com/35354083/67612093-f263d380-f79f-11e9-90dd-654b55a352db.png)

Working correctly on Firefox Nightly 72.0a1 (2019-10-25) (64-bit)
What I've done is to install Tampermonkey and then the 0.2.5 script

**Comment by wahuka** [comment] 2019-10-26 01:25
Working correctly on Firefox Nightly 72.0a1 (2019-10-25) (64-bit)
What I've done is to install Tampermonkey and then the 0.2.5 script
![Screenshot_2019-10-26 YouTube](https://user-images.githubusercontent.com/35354083/67612124-36ef6f00-f7a0-11e9-8124-a1210e2cda65.png)

**Comment by ParticleCore** [comment] 2019-10-26 01:45
@Sukigu Thanks for the updated, definitely better than what I had last suggested.

@wahuka Anything before 1.0.0 is no longer maintained. Some, most or all features might stop working eventually, keep that in mind anyone that wants to rollback to 0.2.5 or below.

**Comment by ledlamp** [comment] 2019-10-30 18:51
![{$errorMessage}](https://2bfm.qonq.gq)
LOL

**Comment by Sukigu** [comment] 2019-11-04 13:17
[Bug 1590898](https://bugzilla.mozilla.org/show_bug.cgi?id=1590898) has landed on Nightly, so Iridium works correctly again without any workaround.

**Comment by ParticleCore** [comment] 2019-11-04 15:02
@Sukigu Appreciate the update, closing this now.

**Closed by ParticleCore** 2019-11-04 15:02 UTC
Labels: firefox bug, wontfix
