### ISSUE TITLE
Request Thumbnails Rotating pictures

### ISSUE THREAD

**Issue by rayman89** [ParticleCore/Iridium#529] opened 2018-08-02 15:56 UTC
Can we have an option that changes the thumbnail on hover showing random parts of the video?

**Comment by ParticleCore** [comment] 2018-08-02 17:43
Duplicate of #261

**Closed by ParticleCore** 2018-08-02 17:43 UTC
Labels: duplicate

**Comment by rayman89** [comment] 2018-08-02 19:02
Does that mean that it's planned to be implemented? On the topic you just said he should separate the requests. Are you planing to implement them all or just a few?

**Comment by ParticleCore** [comment] 2018-08-02 19:03
https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by rayman89** [comment] 2018-08-02 19:15
Yeah I've read that but it's older than the contributing Guide so maybe back then something different applied. 

BTW I noticed they posted an addon https://addons.mozilla.org/en-US/firefox/addon/youtube-pro4/ that is the same as you addon but with the name changed. Even when clicking on the addon button the tab title says iridium.

**Comment by ParticleCore** [comment] 2018-08-02 19:25
Thanks for bringing that up to my attention.
