### ISSUE TITLE
iridium breaks with new youtube beta release

### ISSUE THREAD

**Issue by in1t3r** [ParticleCore/Iridium#679] opened 2019-02-07 03:06 UTC
Iridium breaks the play of youtube videos. Page loads but video not. 
I tried to search for debugs in the console and developer tools but nothing was useful I guess its some function in your extension. I would need to study the extension to find it. Its annoying as there are some nice features that I use to make youtube more usable with your extension.

**Comment by Dr1Rabbit** [comment] 2019-02-07 09:14
I have the same problems. Have to reload each video I open. If Iridium prevents autoplay, then it can`t be played be clicking on thumbnail.

Vivaldi v2.2.1388.37
Iridium v0.2.5

**Comment by Zarggg** [comment] 2019-02-08 03:53
Duplicate of #671, #672. See those threads for an explanation.

**Comment by mattyount28** [comment] 2019-03-12 23:26
I found a temporary fix: go to settings, video, and turn play videos automatically on. :)

**Comment by ParticleCore** [comment] 2019-10-06 22:16
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0

**Closed by ParticleCore** 2019-10-06 22:16 UTC
Labels: wontfix
