### ISSUE TITLE
Disable automatic jump to next video in playlist

### ISSUE THREAD

**Issue by KOT040188** [ParticleCore/Iridium#287] opened 2018-01-16 04:14 UTC
Hi. I want to suggest a new setup for YouTube. I often watch playlists, but I don't like the fact that after viewing the video automatically loads the next video. I would like to have a button in the playlist to turn off automatic jump to the next video. Thank you.

**Comment by ParticleCore** [comment] 2018-01-16 06:45
Duplicate of #78

**Closed by ParticleCore** 2018-01-16 06:45 UTC
Labels: duplicate
