### ISSUE TITLE
https://www.youtube.com/iridium-settings not working

### ISSUE THREAD

**Issue by briank6932** [ParticleCore/Iridium#61] opened 2017-07-15 20:41 UTC
**Browser Name:** Chrome
**Browser Version:** 60.0.3112.66 (Official Build) beta (64-bit)
**Operating System:** Windows 10 version 1703 build 15063.483
**Software Type:** Userscript
**Software Version:** v0.0.2b
**Userscript Manager:** Tampermonkey
**Userscript Version:** v4.3.6
**Problem Description:** https://www.youtube.com/iridium-settings fails to load, there is no error, just a white screen. I have disabled all other scripts or anything else that could possibly mess with the site loading up, however, nothing is working.

**Comment by ParticleCore** [comment] 2017-07-15 21:29
The settings page is working for me with the userscript version on Chrome.

Please follow all the troubleshooting steps as requested, including the step where you test with a new Chrome profile: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by briank6932** [comment] 2017-07-15 21:38
oddly enough, after I enabled Tampermonkey in incognito it worked, then I went back to the non-Incognito window and to my dismay, it started to work again. I'm not quite sure what's causing this issue, but if it happens again I'll make sure to report back with the console error.

**Comment by ParticleCore** [comment] 2017-07-15 21:40
Glad to hear that, please do when it happens again. I will close this for now then.

**Comment by briank6932** [comment] 2017-07-16 00:09
Alright so this issue occurred again and I noticed it only occurs when the media previews are GIFs and not videos, when the previews are videos this issue doesn't occur. 
![image](https://user-images.githubusercontent.com/18603393/28243484-7f5696ac-6999-11e7-8920-ec4717a330db.png)

**Comment by ParticleCore** [comment] 2017-07-16 00:09
This happens after trying to preview a video with the new YouTube 3s preview and then opening the settings menu.

**Comment by briank6932** [comment] 2017-07-16 00:09
yes exactly

**Comment by ParticleCore** [comment] 2017-07-16 00:10
So far there is nothing that should affect one and another, but it is affecting without a doubt. I will try to see what can be done to fix it.

**Comment by briank6932** [comment] 2017-07-16 00:11
I think the best thing to do for now is to just disable the video preview till you find a fix.

**Comment by ParticleCore** [comment] 2017-07-16 00:13
@briank6932 So if you disable the video preview and repeat the process, the settings keep failing to load?

**Comment by briank6932** [comment] 2017-07-16 00:15
While disabled, they load, I'll do a little more fiddling, but that's what's working for now.

**Comment by ParticleCore** [comment] 2017-07-16 00:18
@briank6932 Yeah, this is a problem because I thought I managed to replicate your problem, but as I was testing page exclusion I had mistakenly ignored the settings page. This made me believe I was able to cause the same problem as yours, but it is not. For once, your page is totally blank, while mine wasn't, it still loaded the normal YouTube 404 page since the extension never started due to exclusion.

From your screenshot I can see that you have a lot of extensions, some of which can cause conflicts with Iridium. I would like for you to test this problem with a new clean profile as it is described in the troubleshooting steps and nothing installed except Tampermonkey and Iridium.

**Comment by briank6932** [comment] 2017-07-16 00:21
I did run it in incognito and it did work as I previously mentioned, I was able to replicate the problem even with it turned on, I will do more digging and see what happens.

**Comment by ParticleCore** [comment] 2017-07-16 00:23
Incognito is not a sufficient test case, otherwise I would have listed it in the steps. There can be browser settings changed that can be causing this problem, that is why the step requires a new profile test, not an incognito test.

**Comment by briank6932** [comment] 2017-07-16 00:25
Well, that would be far easier to do on Firefox, which doesn't exhibit this problem, I'll uninstall and reinstall canary and use it with the bare minimum add ons.

**Comment by ParticleCore** [comment] 2017-07-16 00:31
I would suggest to test on the Chrome stable version instead of a version that is not stable, that can very likely be causing this problem, that or the combination of it with Tampermonkey.

It is also a problem if you are still testing it with other extensions besides Tampermonkey and Iridium, we have no idea which one can be causing this problem if this is being caused by one of them in the first place.

If the troubleshooting steps are not followed to the letter then this becomes a useless exercise. They have been designed like that for a reason, they are not just a suggestion for users to follow the way they want. That's the only way to rule out the problem from Iridium when I am unable to replicate it, without it I have no way of fixing a problem I don't have and it is pointless to fix a problem that can be caused by an extension the user felt like always having it running during the tests.

**Comment by briank6932** [comment] 2017-07-16 00:33
I presume it is a Chrome Flag that's causing this problem I tweaked the Chrome flags on chrome beta which I was previously using, I debugged this on Canary which worked fine, I will tamper with some of my flags and extensions to see what's causing this issue.

**Comment by ParticleCore** [comment] 2017-07-16 00:35
Fingers crossed

**Comment by briank6932** [comment] 2017-07-16 01:03
For the life of me, I can't replicate this error, I haven't given up just yet, but it's getting a little annoying.
I viewed the page source of the Chrome Beta (the original browser) and this came up: 
  | <!DOCTYPE html><html><head><style>* { margin:0;padding:0;border:0}html,body{height:100%;}</style><title>404 Not Found</title>
-- | --
  | 
  | </head><body><iframe style="display:block;border:0;" src="/error?src=404&amp;ifr=1&amp;error=" width="100%" height="100%" frameborder="0" scrolling="no"></iframe></body></html>
I also viewed the page source of (the debugging version of chrome) Chrome Canary and this came up:
 | <!DOCTYPE html><html><head><style>* { margin:0;padding:0;border:0}html,body{height:100%;}</style><title>404 Not Found</title>
-- | --
  | 
  | </head><body><iframe style="display:block;border:0;" src="/error?src=404&amp;ifr=1&amp;error=" width="100%" height="100%" frameborder="0" scrolling="no"></iframe></body></html>
It looks like the same error so I think you're right about the extensions/flags things, I'm gonna go tamper a little more, I'll update you when I find anything else that may help out.

**Comment by ParticleCore** [comment] 2017-07-16 01:07
That's the normal YouTube 404 page. Iridium "recycles" that page by emptying it and filling it with its settings menu, this way users will have a common page across versions (add-on and extension versions provide an options button in their browser). That white page you were seeing before was Iridium trying to load its settings menu after stopping the 404 page from loading (hence the console red error message), but something is preventing it from working as it should.

**Comment by briank6932** [comment] 2017-07-16 01:19
I will probably record a video of me tweaking with it because this issue is very unusual.

**Comment by ParticleCore** [comment] 2017-07-16 01:20
It will be all for nothing if you are still not testing it with a stable version of Chrome and with no other extensions running and without a new profile.

**Comment by briank6932** [comment] 2017-07-16 01:22
I did all of those things, it works fine at the bare minimum with Chrome Canary, I'm just trying to find the trigger and it's very triggering XD.

**Comment by ParticleCore** [comment] 2017-07-16 01:23
Oh, so sorry, I thought you meant that the problem was still going on even with the bare minimum.

**Comment by briank6932** [comment] 2017-07-16 01:25
It's fine

**Comment by briank6932** [comment] 2017-07-16 01:37
I have gone through every possible combination this is exhausting I'll get back at it tomorrow.

**Comment by ParticleCore** [comment] 2017-07-16 01:39
I appreciate it, for now I think we can safely assume that this is not related to Iridium. Will close this as such, if you happen to find out the cause do let me know.

**Closed by ParticleCore** 2017-07-16 01:39 UTC
Labels: invalid

**Comment by kalobkalob** [comment] 2018-02-03 04:36
I don't know if anyone's still having this issue but I've found just clearing all cookies from youtube fixes this.

**Comment by ParticleCore** [comment] 2018-02-03 10:22
@kalobkalob Which version of Iridium were you using when that happened?
