### ISSUE TITLE
Comments section not loading sometimes, even when comments set to "show" in settings

### ISSUE THREAD

**Issue by navin09** [ParticleCore/Iridium#409] opened 2018-03-30 04:41 UTC
Errors in console. 

(1)
![iridum-error](https://user-images.githubusercontent.com/120570/38124831-893de75e-3402-11e8-90eb-d7bb09aa8506.png)

(2)
![iridum-error-2](https://user-images.githubusercontent.com/120570/38124845-976a1ed8-3402-11e8-8616-ea6675c027c0.png)

Chrome version: 65.0.3325.181
Iridium version: 0.1.1

**Comment by Atulin** [comment] 2018-03-30 05:06
Possibly related to #408 ?

**Comment by navin09** [comment] 2018-03-30 08:06
@Atulin quite possible. @Auscent in the other thread mentioned that it happens only when 'autoplay' is disabled. I can confirm that enabling autoplay seemed to fix it.  However, I usually browse YT comments with autoplay disabled and the main function that I use Iridium for.

**Comment by ParticleCore** [comment] 2018-03-30 11:00
Duplicate of #408

**Closed by ParticleCore** 2018-03-30 11:00 UTC
Labels: duplicate

**Comment by navin09** [comment] 2018-03-30 15:54
@ParticleCore yes, I realize that from the location of the errors in the code. However, the mini player continued to work fine despite the error; only the comments didn't seem to load. Also, I did read the "Report A Bug" section and made sure that I could reproduce it on a clean profile, with just Iridium installed before I posted. Sorry for not mentioning it in my original post.
