### ISSUE TITLE
mini video does not appear but does play audio when you go to another page

### ISSUE THREAD

**Issue by matjojo** [ParticleCore/Iridium#392] opened 2018-03-18 14:10 UTC
Browser Name: Firefox

  Browser Version: 58.0.2 (64-bit)

  Operating System: Windows 10

  Software Type: Extension

  Software Version: 0.1.0

  Problem Description: mini video does not appear but does play audio when you go to another page 

  Steps to reproduce: Open a video [example link](https://www.youtube.com/watch?v=dQw4w9WgXcQ) play the video, before the vide ends press the hamburger menu on the top left, press subscriptions and hear the video play without the little popup apearing.

**Comment by ParticleCore** [comment] 2018-03-18 14:29
Can't reproduce, please follow the troubleshooting instructions as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by ParticleCore** [comment] 2018-03-18 14:54
Closing for now, if you still have any issues follow the the instructions in my previous reply.

**Closed by ParticleCore** 2018-03-18 14:54 UTC
Labels: invalid
