### ISSUE TITLE
Feature request: Blacklist currently watching channel.

### ISSUE THREAD

**Issue by Whitedoteu** [ParticleCore/Iridium#437] opened 2018-04-29 19:31 UTC
Please add a Button to Blacklist the Video you are watching at the moment.

Sometimes you get the "Next Video" from the same Channel but not always, so I want a button the blacklist the active Video.

**Comment by ParticleCore** [comment] 2018-04-29 21:33
Duplicate of #257

**Closed by ParticleCore** 2018-04-29 21:33 UTC
Labels: duplicate
