### ISSUE TITLE
Request to Add 'Fill Screen' Video Option

### ISSUE THREAD

**Issue by hydriniumh2** [ParticleCore/Iridium#424] opened 2018-04-18 01:07 UTC
Hi, 
Youtube center had a feature which allowed the video to fill the entire screen without going into 'Full Screen', ie you could still scroll down to the comments, search youtube etc similar to Theater view. Youtube plus also had a similar feature that allowed for the video to fit to the width of the screen. I was hoping you might consider adding a 'Fill screen' video resizing option to this addon.
Thank you.

**Comment by ParticleCore** [comment] 2018-04-18 05:52
Duplicate of #418

**Closed by ParticleCore** 2018-04-18 05:52 UTC
Labels: duplicate
