### ISSUE TITLE
Video Don't play on Firefox with Iridum enable

### ISSUE THREAD

**Issue by Kreegola** [ParticleCore/Iridium#734] opened 2019-08-16 17:47 UTC
Video won't start with this addon

**Comment by Zarggg** [comment] 2019-08-16 23:52
Known issue. Turn off the autoplay functionality in Iridium and use Firefox's own settings instead: https://support.mozilla.org/en-US/questions/1238091#answer-1168978

**Comment by ParticleCore** [comment] 2019-10-06 21:54
Please update to version 1.0.0 when available and let me know if this problem is still present.

**Comment by BobbyWibowo** [comment] 2019-10-06 21:58
This only happened when the old version's Prevent Autoplay feature was turned on.
It prevented autoplay indeed, but it also prevented playing the video at all, lmao

**Comment by ParticleCore** [comment] 2019-10-06 22:00
Closing since there are a lot of duplicates of this one.
Duplicate of #671

**Closed by ParticleCore** 2019-10-06 22:00 UTC
Labels: bug

**Comment by ParticleCore** [comment] 2019-10-06 22:01
@BobbyWibowo I'd like to bring that feature back, I miss it too, but I might take advantage of YouTube's native mini player instead of rebuilding it from scratch. We'll see how it goes.

**Comment by BobbyWibowo** [comment] 2019-10-06 22:05
@ParticleCore I sure would love to see it back!
For now I'm really only using the userscript for that feature, and default video resolution, which is surprisingly still work, even with 1.0.0's prevent autoplay feature turned on.
