### ISSUE TITLE
Iridium gone for Chrome Web Store (Not a glitch, but a PROBLEM!)

### ISSUE THREAD

**Issue by EnderPreston** [ParticleCore/Iridium#652] opened 2019-01-03 13:56 UTC
Edit: I just read the announcement, and how silly of me that I didn't notice it. I only have one thing to say now: CURSE YOU GOOGLE!!!!! (rages and throws fit)

Edit 2: I am sorry. I have serious anger issues.

This isn't exactly a glitch with the extension as much as it is an actual problem. Today, I went to get Iridium on a new computer, only to find out it's gone from the web store on every device that I own. By the way, this is NOT a network problem on my end. I have checked other devices and got nothing but the screen shown below. What is going on here? Could someone please look into this!?

![screenshot 2](https://user-images.githubusercontent.com/37002865/50641000-99872e00-0f34-11e9-99a9-d973335c3846.png)

**Comment by ParticleCore** [comment] 2019-01-03 14:09
Duplicate of #648

**Closed by ParticleCore** 2019-01-03 14:09 UTC
Labels: invalid

**Comment by EnderPreston** [comment] 2019-01-03 15:13
Yeah, I apologize for that. I hadn't read the announcement at that point, and I just started typing instinctively. I am very sorry.
