### ISSUE TITLE
The YT videos do not load while Iridium is active all of a sudden

### ISSUE THREAD

**Issue by octapusxft** [ParticleCore/Iridium#826] opened 2020-03-14 06:44 UTC
All of a sudden today, the youtube videos stopped loading while the Iridium add-on is active. They place where the video should be is an empty frame
I already tried reinstalling the add-on but it did not change anything. I did not made any changes on the browser, it just started happening
https://i.imgur.com/1NQmDDM.png
---

software details:
````
manifestVersion: 1.2.4
cookieEnabled: true
doNotTrack: 1
language: en-US
buildID: 20200309095159
name: Firefox
vendor: Mozilla
version: 74.0
arch: x86-64
os: win
````

steps to recreate the problem:
I did not do anything particularly different other than trying to look at my "watch later" playlist.

additional information that could be helpful:

**Comment by ParticleCore** [comment] 2020-03-14 11:57
When that happens open the browser console (F12 key) and see if it says the following:

> uncaught exception: out of memory

**Comment by octapusxft** [comment] 2020-03-14 16:14
Yes it has exactly that "uncaught exception: out of memory" message !

**Comment by ParticleCore** [comment] 2020-03-14 16:22
Closing as duplicate of #825

**Closed by ParticleCore** 2020-03-14 16:22 UTC
Labels: duplicate
