### ISSUE TITLE
Feature Request: "Don't autoplay but start buffering"

### ISSUE THREAD

**Issue by Mav3r1x** [ParticleCore/Iridium#271] opened 2017-12-20 17:36 UTC
I guess the title explains it all. It would be really useful, if you're opening multiple youtube tabs.

**Comment by ParticleCore** [comment] 2017-12-20 18:23
Duplicate of https://github.com/ParticleCore/Iridium/issues/11

**Closed by ParticleCore** 2017-12-20 18:23 UTC
Labels: duplicate
