### ISSUE TITLE
[Feature request] Allow/add scaling for non 16:9 displays

### ISSUE THREAD

**Issue by pufcio** [ParticleCore/Iridium#572] opened 2018-09-23 10:09 UTC
Hello,

The feature that I miss the most from the older version of plugin was to set the player size. I could meddle with it a bit and find a proper value so it would be ideal for every device that I use.
Since my primary workstation has a 4:3 screen and I do watch videos sometimes, they fill like 80% of space they should. I suspect a similar issue may occur if someone's got a 21:9 display or some others, can't tell.
Is there a way to add a switch or anything that would allow me to extend the area vertically so the videos would fill space horizontally?

**Comment by ParticleCore** [comment] 2018-09-23 12:51
Duplicate of #341

**Closed by ParticleCore** 2018-09-23 12:51 UTC
Labels: duplicate
