### ISSUE TITLE
[Feature] Split "Auto play videos" and "Auto play lists"

### ISSUE THREAD

**Issue by ggr18** [ParticleCore/Iridium#597] opened 2018-10-26 13:23 UTC
If you want to listen an entire list you need to play every video individually. A nice feature would be that if I'm looking at individual videos, then the auto-play works as intended, but if I'm on a list then the option overrides for "auto play when on a list".

**Comment by ParticleCore** [comment] 2018-10-26 16:22
Duplicate of #78

**Closed by ParticleCore** 2018-10-26 16:22 UTC
Labels: duplicate
