### ISSUE TITLE
Feature replay video

### ISSUE THREAD

**Issue by in1t3r** [ParticleCore/Iridium#419] opened 2018-04-05 21:18 UTC
Feature request is:

- [ ] reimplement a autorepeat video to the toolbar as a toggle switch.

I used this extension in previous version as youtubeplus and particle as I usually use nightly version of the firefox.
The one feature that I miss the most from old extension is ability to do reply automatically. It is very useful when you want to put a video or song in reply one mode. As you tube still do have that option but you need to click it I guess it wouldn't be hard too hook it up again to a toggle mode in toolbar under the video section. 
I still use this extension and this is the option that I need most.

I would write this addition myself but I do not really do JS as I do C++, C, Java, Python. 
Don't try to brag or to diminish the JS as programming language just I do mostly Application, Embedded and System level coding so never had time to waste on too much changing technologies like JS and its frameworks are.

If nothing and you dont have time for this feature I might later do re-implement the similar addon for firefox if I find time to learn more JS. 
Its unfortunate that you do not use GPL for your source code as project would grow faster and be developed much faster better and more stable.
I guess if you do not consider constructive criticism in this feature request then I do not really care whether you delete it or not.

**Comment by ParticleCore** [comment] 2018-04-05 21:49
Duplicate of #12 

> Its unfortunate that you do not use GPL for your source code as project would grow faster and be developed much faster better and more stable.

I understand the argument, but it is not applicable here due to a few blockades:
 - Mozilla has a very strict policy for all add-ons submitted to their store, which means any "bad" code that slips through will become a problem
 - I would have to inspect every single submission to ensure that there would be no "bad" code (something as simple as an `innerHTML` assigned to a variable that only contains static text), in a sense I would have to be a Mozilla reviewer
- I would have to teach contributors how the extension is structured and all the logic that only I know, because most just don't bother reading anything these days
 - I would have to explain over and over again every time another user would try to make a pull request for a video/audio download feature why it can't be implemented since Chrome store would ban the extension
- I already hardly have time to fix bugs and develop more features, let alone make sure the code contributions are safe and with the correct structure

And I don't understand your last phrase? I do appreciate any constructive criticism, if I gave the wrong idea somehow then I apologize, it was not my intention.

**Closed by ParticleCore** 2018-04-05 21:49 UTC
Labels: feature

**Comment by in1t3r** [comment] 2018-04-05 23:48
Thank you for a reply and sorry for that last phrase I thought that restrictive license was because of need to have more command over the codebase and for copyright.
Didn't know that nowadays Mozilla have a strict webextensions code checking code checking problem.
