### ISSUE TITLE
Playlist options not working on Chrome or Firefox

### ISSUE THREAD

**Issue by Jorvalt** [ParticleCore/Iridium#715] opened 2019-05-08 23:02 UTC
I click the little (...) button at the top of the playlist and nothing happens.

**Comment by JonathanPalmerGD** [comment] 2019-05-09 18:36
I am experiencing this problem as well. When I disable Iridium, the option returns.

**Comment by Matakor** [comment] 2019-05-09 22:44
Playlist appears to be completely broken for me. It will move to the second video, then just repeat that same video infinitely. I can't watch a playlist anymore. This started after the reverse controls vanished.

**Comment by milklineep** [comment] 2019-05-14 19:08
Duplicate of  #707 for the first two comments

**Comment by martixy** [comment] 2019-05-19 13:39
Can confirm.

The only reason I used the extension was the reverse playlist option. Now that doesn't work.

**Comment by Mattia98** [comment] 2019-05-24 16:04
I can confirm this problem.

**Comment by KenjiTakahashi** [comment] 2019-06-01 08:16
Error from console, when pressing the (...) button:
```
Uncaught TypeError: Cannot read property 'fetchMenuCommand' of undefined
    at HTMLElement.onOverflowTap_ (desktop_polymer_sel_auto_svg_watch_v2.js:10304)
    at HTMLElement.<anonymous> (desktop_polymer_sel_auto_svg_watch_v2.js:7157)
    at HTMLElement.ob [as __shady_dispatchEvent] (webcomponents-sd.js:34)
    at J.k.dispatchEvent (webcomponents-sd.js:80)
    at _fire$$module$third_party$javascript$polymer$v2$polymer$lib$utils$gestures (desktop_polymer_sel_auto_svg_watch_v2.js:7400)
    at RV (desktop_polymer_sel_auto_svg_watch_v2.js:7424)
    at Object.click (desktop_polymer_sel_auto_svg_watch_v2.js:7421)
    at HTMLElement._handleNative$$module$third_party$javascript$polymer$v2$polymer$lib$utils$gestures (desktop_polymer_sel_auto_svg_watch_v2.js:7390)
```

**Comment by Mattia98** [comment] 2019-06-04 11:38
Is this extension abandoned?

**Comment by Zarggg** [comment] 2019-06-04 19:22
See issue #673

**Comment by ParticleCore** [comment] 2019-10-06 22:09
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0

**Closed by ParticleCore** 2019-10-06 22:09 UTC
Labels: wontfix
