### ISSUE TITLE
Video player sits on a black screen (with ad URL) then resumes playing.

### ISSUE THREAD

**Issue by tgp1994** [ParticleCore/Iridium#194] opened 2017-09-25 23:56 UTC
Browser Name: Mozilla Firefox
Browser Version: 55.0.3 (32-bit), normal release channel.
Operating System: Windows 10 64-bit Version 1703, build 15063.413
Software Type: Userscript
Software Version: 0.3.0b
Userscript Manager: Greasemonkey
Userscript Version: 3.14
Problem Description: Video player sits on a black screen (with ad URL) then resumes playing when a fullscreen ad is requested.
Steps to reproduce:

1. Create fresh Firefox profile
2. Install Greasemonkey from the extension store, then download Iridium from GitHub
3. In Iridium, enable the **Allow ads on videos** option under Video
3. Go to Youtube and find a video that has ads enabled with full-video ads (for example, see this random gaming video: https://www.youtube.com/watch?v=nV8XaF2Rrrk
4. Note how when the video starts playing, it begins with a black screen and the advertisement URL at the bottom left. Note that none of the video controls are available at this point, and the player cannot be resized.

Additional details: 

For the past few weeks when I load a video with ads, the video player will freeze with a black screen and the url to the ad at the bottom left. Pretty much all Youtube UI will be unresponsive at this point. It will wait for about 6 seconds or so, then resume playing the requested video. For me, it always seems to be the Grammarly (or Wix) advertisements that do this. If Iridium is disabled in the Greasemonkey scripts, or ad blocking is disabled in Iridium's options, then the ads play normally.

**Comment by tgp1994** [comment] 2017-09-26 17:06
I apologize for not reading the contributing guidelines before posting. Here's what I've discovered: after confirming that I was still experiencing the issue as of this morning, I've reset the extension settings to their defaults, and this has appeared to have fixed the issue. I'll try resetting my settings to find out what was causing it in the first place.

**Comment by ParticleCore** [comment] 2017-09-26 17:30
Make sure you follow all the troubleshooting steps since this could be another extension causing problems with Iridium.

**Comment by tgp1994** [comment] 2017-09-26 17:32
Thanks @ParticleCore , I've just completed the troubleshooting steps and I can confirm that the issue persists even under a fresh profile. Please see my OP; I've updated it with the relevant information from the contributing guide. I should also probably mention that I've noticed this on another machine with Iridium installed.

**Comment by ParticleCore** [comment] 2017-09-26 17:39
Your detailed explanation makes believe that I overlooked a condition or two, will check it out as soon as I can, thanks!

**Comment by ParticleCore** [comment] 2017-09-30 01:22
I haven't forgotten about this, I just haven't been able to reproduce it, but I also haven't had that much time for it, hope to have more time this weekend to get around this issue. I apologize for this.

**Comment by tgp1994** [comment] 2017-09-30 02:09
Not a problem, somehow I've managed to almost forget about it! I think I
might have disabled the Ad block feature so maybe uBlock is catching them
now.

**Comment by ParticleCore** [comment] 2017-10-01 13:57
I was finally able to replicate this problem, it is as you described. However it only lasts for the supposedly duration of the ad, meaning that if the ad is just 30s, it will stay black for that time and then the video starts playing. Problem is when an ad is actually another YouTube video that can go as long as 5minutes or more.

Will try to find a fix for this asap.

**Comment by ParticleCore** [comment] 2017-10-02 18:16
This should be fixed in version 0.3.1b

**Comment by tgp1994** [comment] 2017-10-02 18:27
I'm not sure this is completely tackled yet. I updated to 0.3.2b and verified that ad blocking works normally. But lets say I'd like to support my subscribed channels (which is a great feature btw). When I enable this feature, I again encounter the issue of videos sitting at a black screen, but only when the ad plays. This time it was for some sort of Marvel advertisement.

**Comment by TopFuel** [comment] 2017-10-02 22:10
I can confirm what @tgp1994 said above.
Here is a screenshot of the problem: https://i.imgur.com/kzUSA3v.png

**Comment by ParticleCore** [comment] 2017-10-03 01:36
Aw, thought I got it all. Will try to see what is going on this time. Sorry for the delay, but it is not often video ads show up on my end.

**Comment by tgp1994** [comment] 2017-10-03 02:02
Thanks for your hard work on this. I'd think you should be working for YouTube by now. :)

**Comment by ParticleCore** [comment] 2017-10-03 18:03
Found it, will try to fix it asap.

**Comment by ParticleCore** [comment] 2017-10-04 18:32
This should finally be fixed on version 0.3.3b

**Closed by ParticleCore** 2017-10-04 18:32 UTC
Labels: beta, bug

**Comment by maci3k** [comment] 2017-10-05 10:59
I can also confirm that issue is solved now.
Thank you.
