### ISSUE TITLE
Video thumbnail is missing at video page

### ISSUE THREAD

**Issue by adeep** [ParticleCore/Iridium#176] opened 2017-09-18 19:10 UTC
Browser Name: (Chrome)

Browser Version: (61.0.3163.91)

Operating System: (Windows 10)

Software Type: Userscript

Software Version: (0.2.8b)

Userscript Manager: (Tampermonkey)

Userscript Version: (4.3.6)

Problem Description: Video thumbnails is missing at videoplayer 

Steps to reproduce: Disable autoplay for videos load video page. Thumbnail is missing and replaced with gray youtube three dot logo (see below)

![screenshot_2](https://user-images.githubusercontent.com/374042/30559423-4ad44da0-9cbd-11e7-9db2-8ae14e084503.png)
![screenshot_3](https://user-images.githubusercontent.com/374042/30559425-4b4783e2-9cbd-11e7-83f2-1528d3702b08.png)

**Comment by ParticleCore** [comment] 2017-09-18 19:26
Duplicate of https://github.com/ParticleCore/Iridium/issues/174

**Comment by ParticleCore** [comment] 2017-09-18 19:27
I should probably consider checking if the image exists or not to avoid any more confusion like this, but I don't think it will be worth it.

**Closed by ParticleCore** 2017-09-18 19:26 UTC
Labels: duplicate

**Comment by adeep** [comment] 2017-09-18 19:34
Sorry for duplicate, I am trying to read all thing but sometimes one word is cause to miss it (like autoplay turned off)
If you can make it to check if there is exist will be good. But You can make that feature off by default to avoid gray icon. If someone want it to HQ thumnail can switch it on. 
Note: I assume it on by default, cause i reset the script and its on still.

**Comment by ParticleCore** [comment] 2017-09-18 19:43
I will try, but things don't look very good since I first tried it in YT+ back in 2015, same problems exist today. I will do some tests and see if it works well.

**Comment by ParticleCore** [comment] 2017-09-18 23:39
The new version comes with an attempt at solving this issue, defaulting to standard definition thumbnail if high quality is not found. If you wish to try it out again let me know if it works well for you.
