### ISSUE TITLE
Videos fail to play entirely when "Play videos automatically" is unchecked.

### ISSUE THREAD

**Issue by doomcup** [ParticleCore/Iridium#672] opened 2019-01-29 12:19 UTC
Browser is Firefox Quantum 64.0.2 under linux.

When "Play videos automatically" is turned off, videos will fail to load and play. No amount of clicking or changing quality will make videos play. Videos will only play when the option is turned on.

**Comment by Nawaf-NM** [comment] 2019-01-29 12:39
I agree with you, I can not play the video definitively.

i used:  Firefox Quantum 64.0.2

**Comment by juozaspo** [comment] 2019-01-29 12:57
Just noticed this recently. Seems youtube changed something. In firefox, when autoplay is enabled and _about:config_ setting **media.autoplay.default** is set to **1** video does not auto-play on first load, other videos do. To stop autoplay for other videos, disable autoplay button before playing next video, re-enable it before page refresh or visiting a link from bookmarks and/or some page that's not youtube, also making sure **media.autoplay.default** in _about:config_ is **1**.

Firefox 64.0
Greasemonkey 4.7
Iridium 0.2.5

**Comment by jrial** [comment] 2019-01-29 15:23
Duplicate of #671

**Comment by AlphaTheOmega** [comment] 2019-01-29 15:25
Same for me with windows 10 firefox. Videos wouldn't play so i had to disable iridium for the time being. Youtube did something and now they're clashing

**Comment by Cryde** [comment] 2019-01-30 19:09
@AlphaTheOmega yes indeed

**Comment by Anutrix** [comment] 2019-02-02 05:51
Same here

**Comment by WirlyWirlyPool** [comment] 2019-02-03 18:33
Also experiencing this on the latest version of FireFox via PortableApps.

**Comment by LeeBinder** [comment] 2019-02-04 18:21
> Same here. Disabled Iridium for now

why? Just check "Play videos automatically". Or you trash your entire car when one radio speaker goes scratchy? Overkill, buddy..

**Comment by webfischi** [comment] 2019-03-28 21:26
This feature needs to be redone, because Firefox 66 now has a media auto play blocker build in

**Comment by ParticleCore** [comment] 2019-06-21 12:43
Duplicate of #671

**Closed by ParticleCore** 2019-06-21 12:43 UTC
Labels: duplicate
