### ISSUE TITLE
[Feature Request] Add Setting to Disable Fullscreen "Scroll for details"

### ISSUE THREAD

**Issue by Shananiganeer** [ParticleCore/Iridium#628] opened 2018-11-13 20:51 UTC
YouTube has implemented a new "feature" that allows for fullscreen videos to be scrolled out of. Add a setting to disable this functionality.

It looks like crap and defies the purpose of fullscreen:
https://i.imgur.com/xLkYTEq.png

**Comment by ParticleCore** [comment] 2018-11-13 20:53
Duplicate of #624

**Closed by ParticleCore** 2018-11-13 20:53 UTC
Labels: duplicate

**Comment by Shananiganeer** [comment] 2018-11-13 20:58
Sorry, saw that other issue and didn't realize you were using labeled closed issues for tracking.
