### ISSUE TITLE
Way to keep the autoplay on the top right always turned off?

### ISSUE THREAD

**Issue by annadane** [ParticleCore/Iridium#436] opened 2018-04-29 18:48 UTC
Hi; Iridium has an option to have autoplay off, but by "autoplay" they mean the current video... is there a way to turn off the autoplay on the top right, aka go to next video in the list with the "up next" selection?

**Comment by ParticleCore** [comment] 2018-04-29 21:34
Duplicate of #138

**Closed by ParticleCore** 2018-04-29 21:34 UTC
Labels: duplicate
