### ISSUE TITLE
Can't play videos on chrome with Iridium enable

### ISSUE THREAD

**Issue by etshy** [ParticleCore/Iridium#730] opened 2019-07-28 19:17 UTC
Since today I couldn't play video on chrome with iridium enabled (It's loading indefinitely).

Videos worked great on firefox and on chrom after I disabled Iridium.

Not sure what I can do to help with the debug, so please tell if I can help.

**Comment by andrewjmetzger** [comment] 2019-07-30 23:54
Hi @etshy, thanks for raising this issue! 

Sadly, development of Iridium is currently on-hold. However, as a temporary fix, please try turning *off* Iridum's built-in ad removal in the extension Video settings, as seen in this screenshot below:
![2019-07-30_19-50-48](https://user-images.githubusercontent.com/590246/62173300-83432400-b303-11e9-933e-7312dc061266.png)

Don't worry, you can still use another adblocker [like uBlock Origin](https://github.com/gorhill/uBlock), but disabling the one in Iridium should allow videos to play again.

If you have any questions, please reply and let me know. Hope this helps! 😃

**Comment by dogancelik** [comment] 2019-08-08 15:13
* [x] Allow ads on videos
* [ ] Allow ads only on videos of subscribed channels

I have checked the settings like above. It didn't fix the issue in the userscript version.

(Using Tampermonkey 4.9.5941 on Firefox 68.0.1)

**Comment by andrewjmetzger** [comment] 2019-08-08 15:17
What version is the userscript, @dogancelik?

**Comment by dogancelik** [comment] 2019-08-08 15:25
The one from [Greasefork](https://greasyfork.org/en/scripts/37902-iridium), 0.2.5

**Comment by andrewjmetzger** [comment] 2019-08-08 15:30
Thanks @dogancelik. Unfortunately, since Iridium is no longer being maintained, I would suggest moving to another extension. For Chrome, [ImprovedTube](http://improvedtube.com/) seems to work well, but I have not been able to find a version for Firefox.

**Comment by etshy** [comment] 2019-08-08 17:19
I can confirm it doesn't work with the ads parameter as shown.
extension installed from chromestore

**Comment by ParticleCore** [comment] 2019-08-08 17:42
@andrewjmetzger Let's try to avoid using this repository to publicize other add-on's, it's not like people can't look alternatives for themselves, otherwise users will start using this repository to seek support for the suggestions being made here which is not the reason for this place.

**Comment by ParticleCore** [comment] 2019-10-06 22:02
Duplicate of #671

**Closed by ParticleCore** 2019-10-06 22:02 UTC
