### ISSUE TITLE
Feature request: Resize the video window that appears when scrolling

### ISSUE THREAD

**Issue by HubKing** [ParticleCore/Iridium#729] opened 2019-07-19 17:23 UTC
The video window is too small for me. It would be more useful if I could resize the video window using mouse. If that takes too much coding to implement, how about just letting users specify the video window dimensions in the settings?

**Comment by ParticleCore** [comment] 2019-10-06 22:06
Duplicate of #360

**Closed by ParticleCore** 2019-10-06 22:06 UTC
