### ISSUE TITLE
Autoplay only in Youtube Playlist - feature

### ISSUE THREAD

**Issue by M0lyk** [ParticleCore/Iridium#480] opened 2018-06-17 13:00 UTC
Hi guys,

No bug here, I'm asking for a new feature : l prefer the manuel play mode, but when playing a Youtube playlist, I have to switch to the Autoplay mode. Is it possible to activate the autoplay only when playing a playlit ?
Thank you!

**Comment by ParticleCore** [comment] 2018-06-17 13:01
Duplicate of #78

**Closed by ParticleCore** 2018-06-17 13:01 UTC
Labels: duplicate
