### ISSUE TITLE
"Watch later" playlist is empty around video

### ISSUE THREAD

**Issue by 2tolik** [ParticleCore/Iridium#272] opened 2017-12-26 11:13 UTC
Browser Name:  Chrome 
  Browser Version: 63.0.3239.84 (Official Build) (64-bit)
  Operating System: Win10Pro
  Software Type: UserScript (master repo)
  Software Version: 0.4.1b
  Userscript Manager: AceScript
  Userscript Version: 1.0.8
  Problem Description: Entire space around video is blank&black 
  Steps to reproduce: open https://www.youtube.com/playlist?list=WL and hit "Play All"
  Additional details: Expected: list of videos and video controls should be visible just like for any other playlist in "Play all" mode

**Comment by ParticleCore** [comment] 2017-12-26 13:21
When I click that link it only shows "This playlist does not exist". Additionally, support is only being provided for Greasemonkey and Tampermonkey userscript managers. AceScript is not included, make sure this issue is not being caused by using a non-supported userscript manager.

**Comment by ParticleCore** [comment] 2017-12-26 13:24
I have clicked "Play all" on my own watch later playlist and everything is working correctly. Please provide a screenshot example that shows the problem you are trying to describe.

**Comment by ParticleCore** [comment] 2017-12-29 14:03
Closing this for now.

**Closed by ParticleCore** 2017-12-29 14:03 UTC
Labels: invalid

**Comment by dealien** [comment] 2017-12-30 17:59
After some testing on behalf of @2tolik, it looks to me as if Iridium works about the same in AceScript as it does in Tampermonkey (and I assume Greasemonkey), albeit with noticeably reduced performance (about 1200 ms longer load time). This was tested in the exact same environment and with the exact specifications that @2tolik provided in their original post. 

_(Please note that I fully support @ParticleCore's decision not to support user script managers other than Tampermonkey or Greasemonkey and that this comment is not meant to endorse their use in any way. I just figured I might step in and offer my help with this issue if possible.)_ 

Anyway, while I was unable to reproduce the problem exactly, I did notice that during the static loading process (as opposed to [YouTube's new dynamic loading system](https://youtube.github.io/spfjs/)) the page hangs a lot longer on the blank video page blank template than normal. 

<img width="1680" alt="youtube video page template" src="https://user-images.githubusercontent.com/11463644/34456084-25893070-ed5c-11e7-9e48-4df1554307de.png">

During testing, this page appeared only for a split second, after which the playlist loaded with the video still missing. 

<img width="1680" alt="youtube video page template with playlist" src="https://user-images.githubusercontent.com/11463644/34456109-c20f08de-ed5c-11e7-85be-e0acb683fecc.png">

That page was visible for about a second, after which the video finally loaded and began playing. 

<img width="1680" alt="youtube video page" src="https://user-images.githubusercontent.com/11463644/34456304-3a4ba8c6-ed61-11e7-83d3-58d1ecf34033.png">

However, I was unable to replicate a situation where the page load hangs on a blank page. 

All in all, I don't believe this to be an issue with the software @2g4y1. It's more likely to be a separate issue on your end. I hope that helps!

**Comment by 2tolik** [comment] 2018-01-02 09:58
I can reproduce it, still (see screenshots). 
Looks like "Watch Later" is different to other "playlists", with combination of my Iridium settings and pre-steps may cause this problem (my WatchLater playlist is huge as well).
I will switch to Tampermonkey and provide more reliable steps + screenshots next time.

![image](https://user-images.githubusercontent.com/5185107/34480254-fea62c06-efb3-11e7-9170-480bc2583e8c.png)

**Comment by 2tolik** [comment] 2018-01-25 12:30
It is false alarm / definitely not Iridium problem as it happens with disabled Iridium as well.
Must be related to size of WatchLater list. Mine is 1500+

**Comment by 2tolik** [comment] 2018-01-25 12:33
Maybe there is way to fix (lazy-load optimize) it via UserScript, though ;)
