### ISSUE TITLE
Request: Volume change magnitude control

### ISSUE THREAD

**Issue by ZviHantsis** [ParticleCore/Iridium#471] opened 2018-06-06 01:34 UTC
Hey guys!
Great extension! I'm very pleased of it.

Just a request regarding volume jumps: The script has a hard-coded volume jump of magnitude 5 (line 3579). For my hardware, this is very sensitive and +/-5 can make it intensely loud or quite suddenly. I change it to 1 or 2 at every version update.

My request is that this is that this setting can be part of the configuration (maybe a small rubric next to the checkbox with the number?) or just save it from version to version.

Thanks!

**Comment by ParticleCore** [comment] 2018-06-06 01:37
Duplicate of #457

**Comment by ParticleCore** [comment] 2018-06-06 01:37
Better make this one the actually request instead of the other one that was linked before.

**Closed by ParticleCore** 2018-06-06 01:37 UTC
Labels: duplicate
