### ISSUE TITLE
Script not being identified as a userscript on Greasemonkey 4.0 on Firefox 57

### ISSUE THREAD

**Issue by BlueNinja0** [ParticleCore/Iridium#239] opened 2017-11-19 18:42 UTC
Clicking the script available in the Downloads page opens the script in plain text in Greasemonkey 4.0 on Firefox 57, probably because of the Greasemonkey 4.0 backwards incompatibility.

I assume this is not going to affect the Firefox Addon version.

**Comment by ParticleCore** [comment] 2017-11-19 19:11
Duplicate of #235

**Closed by ParticleCore** 2017-11-19 19:11 UTC
Labels: duplicate

**Comment by BlueNinja0** [comment] 2017-11-19 19:17
My apologies.
