### ISSUE TITLE
No Reverse Playlist Button

### ISSUE THREAD

**Issue by DaveyJake** [ParticleCore/Iridium#989] opened 2024-07-26 15:25 UTC
I do not see a reverse playlist button anywhere when trying to watch a playlist.  See playlist [here](https://www.youtube.com/playlist?list=UUKuOlCSiWc_mkl4sIv0LO5A).

![Screenshot 2024-07-26 at 10 23 56](https://github.com/user-attachments/assets/3bc71ab2-7cca-4281-b008-270c854ee151)

**Comment by BradyThe** [comment] 2024-08-20 20:01
The button doesn't exist in the overview, but is there in the videoplayer view. The overview "Play All" and "Shuffle" buttons redirect to the videoplayer, so while it might be a QOL issue, it is not function-breaking, in my opinion.
![image](https://github.com/user-attachments/assets/5da97b59-24da-467d-86d8-03ef7f77b92d)

**Comment by ParticleCore** [comment] 2024-08-20 21:16
> The button doesn't exist in the overview, but is there in the [videoplayer view](https://www.youtube.com/watch?v=tNn7GCJcJTI&list=UUKuOlCSiWc_mkl4sIv0LO5A&index=1). The overview "Play All" and "Shuffle" buttons redirect to the videoplayer, so while it might be a QOL issue, it is not function-breaking, in my opinion. ![image](https://private-user-images.githubusercontent.com/8181555/359626672-5da97b59-24da-467d-86d8-03ef7f77b92d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODg3MTgsIm5iZiI6MTcyNDE4ODQxOCwicGF0aCI6Ii84MTgxNTU1LzM1OTYyNjY3Mi01ZGE5N2I1OS0yNGRhLTQ2N2QtODZkOC0wM2VmN2Y3N2I5MmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMjExMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NhMDg5ZTUzODI1NzI1Yzc3MWM4YzhlZWMxMDU4ZTU1NzA5OTYwMWU3ZTIwNzA2NzNkNDQ1ZjMwOTY1OGUyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PoZCu5RjMyFbawGOfvXayKIyshEIQJMffpsGlv0PuJk)

I thought he was referring to a new playlist layout that I was still waiting to get, but never arrived. If that is the case then yes, you are correct, this is not a bug. The buttons are only available during playlist playback.

@DaveyJake can you confirm this?

**Comment by ParticleCore** [comment] 2024-09-12 03:32
I'll be closing this since it appears the issue was simply a misunderstanding of where the feature is available at.

**Closed by ParticleCore** 2024-09-12 03:32 UTC
Labels: invalid

**Comment by DaveyJake** [comment] 2024-09-18 06:36
Apologies for not seeing this sooner.  It was a misunderstanding on my part.
