### ISSUE TITLE
Iridium stopped functioning

### ISSUE THREAD

**Issue by ColonelGerdauf** [ParticleCore/Iridium#749] opened 2019-10-08 15:21 UTC
So I have the extension installed on my Firefox browser, and everything was going fine, when suddenly it is just gone - no icon anywhere on the floating header, and none of the settings that I had applied previously seem to take effect.

I have done troubleshooting as best as I could, and I could not find any external conflicts that would have caused it to malfunction. For instance, I had disabled all of my other extensions, Iridium still won't show up. I have reset my Firefox config tweaks, reset content filtering, and disabled performance optimizations on Firefox. Still nothing.

With what little I understand from this, the issue seems to stem in either the Iridium extension itself, a recent Firefox update, or some combination of the two.

**Comment by adamxp12** [comment] 2019-10-08 15:53
The author pushed an update out which removed ALL the features... instead of just leaving the old version up while he/she worked on the new version they decided it was best to ruin the extension by making sure no one can use it. Disappointed to say the least. should not of been pushed to the firefox store

**Comment by ColonelGerdauf** [comment] 2019-10-08 16:31
But that would make no sense, as it was functional until this morning, and the latest commit to master was 2 days ago. If you are so concerned about the lack of Chrome and Userscript compatibility , then it is safe to say that you are not aware of the technical limitations of Userscripts and Blink, as well as the actions of Google/Alphabet as of late.

I am sorry to say, but your complaint is of questionable relevance to my issue.

**Comment by adamxp12** [comment] 2019-10-08 16:41
I dont care about chrome/userscript. I use firefox. the update only reached my computer today too (Firefox addons take a while to get approved for each update). I am not pleased as I now have a bare basic youtube. I know I can downgrade but I shouldnt have to.

My problem is the previous version on firefox was working fine for the most part. Why should the dev push a version that nerfs it on firefox? even if its temporary while they work on the new one. the new one should have been pushed to github under a new branch but not to the firefox add-ons page and thus to existing users who have all simultaneously just had an addon they use become useless

its the equivalent of Apple making a new version of iOS. but starting from scratch. removing everything but the flashlight feature then pushing it out to users.

**Comment by Z3ROGRAV1TYx** [comment] 2019-10-08 17:57
>instead of just leaving the old version up while he/she worked on the new version they decided it was best to ruin the extension by making sure no one can use it. Disappointed to say the least.

This. I don't understand what the point of this was. It was not a smart move at all. I shouldn't have to manually download an old version to restore functionallity. He should've left the old version published to Firefox addons and then just worked on the rewrite on his own time and when it was ready, then push it. Actually frustrating.

**Comment by adamxp12** [comment] 2019-10-08 18:02
@Z3ROGRAV1TYx I wouldnt be mad if it had at least half of the original features. but it has 2x. a dark theme which already exists... and prevent autoplay... I cant see why anyone would want the last feature but hey its there if you want it.

No channel blacklists,  no UI improvements, no video quality defaults etc. 

I understand why the addon is being rewritten. what I dont understand is why the new and featureless version got pushed to users. I have never made a firefox addon but surely someone sat down and actually clicked submit on a form to have 1.0.0 submitted to users and thought that was a great idea :|

At least I am not the only one who can see the backwards nature of this update (even if long term this update will be better as it gets rid of userscripts in favour of native firefox code if I am not mistaken??) just not ready for users yet

**Comment by ParticleCore** [comment] 2019-10-08 18:12
Duplicate of #745

**Closed by ParticleCore** 2019-10-08 18:12 UTC
Labels: duplicate

**Comment by Z3ROGRAV1TYx** [comment] 2019-10-11 02:13
>what I dont understand is why the new and featureless version got pushed to users.

This was exactly my point. Completely agree.

**Comment by DebSec** [comment] 2019-10-14 21:46
Firefox 60.9.0esr Broken
Since the v1.0 update the add-on does not work anymore. Nothing shows for settings or buttons. Debian Buster.
