### ISSUE TITLE
[Feature request] Playback speed control for more than 2x

### ISSUE THREAD

**Issue by CodingSadhu** [ParticleCore/Iridium#637] opened 2018-12-04 10:57 UTC
I think it not very hard to do this. Please see this extension
https://chrome.google.com/webstore/detail/youtube-playback-speed-co/hdannnflhlmdablckfkjpleikpphncik
Can you merge this feature into iridium??

**Comment by ParticleCore** [comment] 2018-12-04 21:04
Duplicate of #476

**Closed by ParticleCore** 2018-12-04 21:04 UTC
Labels: duplicate
