### ISSUE TITLE
Settings Glitches

### ISSUE THREAD

**Issue by NovaViper** [ParticleCore/Iridium#97] opened 2017-08-03 20:00 UTC
Browser Name: Vivaldi/Chrome

  Browser Version: Vivaldi: 1.10.867.46 (32bit), Chrome: 59.0.3071.115 (64 bit)

  Operating System: Windows 10 64bit

  Software Type: Userscript

  Software Version: 0.0.7b

  Userscript Manager: Tapermonkey

  Userscript Version: 0.0.7

  Problem Description: I enable the allow subtitles setting and allow loudness normalization settings, they never seem to activate after I refresh the pages. Also to note, the subtitles button seems to completely disappear when I install the userscript (as it is turned off by default) however, with the setting turned on, the button still doesn't appear. The opposite applies to both the thumbnail video settings and the shift volume thumbnail video switch; when the settings is turned off, the thumbnail still play videos and I can still toggle the volume of the thumbnail video

  Steps to reproduce: Turn on either the allow subtitles or allow loudness normalization settings. Turn off the video thumbnail and shift volume thumbnail video switch settings

  Additional details:

**Comment by ParticleCore** [comment] 2017-08-03 20:04
Please be more clear about the problem and the steps to reproduce it, I don't understand what you are trying to explain.

**Comment by NovaViper** [comment] 2017-08-03 20:32
@ParticleCore The strangest thing is, I go into the settings and turn on the 'Allow Subtitles' and 'Allow Loudness Normalization' options, then I close the settings page and refresh the page, and it doesn't to 'activate' them (the subtitles button is still gone and no volume difference whatsoever). Now with the thumbnail videos, if I turn the setting off, then refresh the page, it doesn't turn the setting off at all, as I still can get thumbnail videos

**Comment by ParticleCore** [comment] 2017-08-03 20:41
The instructions clearly explain not to couple issues into one:

>For any issue created it must only refer to one issue only.

https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md


So please remember that in the future.

As for the subtitles problem, this is a side-effect of a recent update. If you allow ads I believe you will see the subtitles available again, in which case this is a duplicate of https://github.com/ParticleCore/Iridium/issues/92

Which I haven't had the time to fix it, unfortunately.

As for the thumbnail videos, when I turn that option off the it correctly turns off full thumbnail video playback, leaving the YouTube native 3s video preview: https://www.reddit.com/r/youtube/comments/6nvi8g/this_is_why_i_love_the_new_thumbnail_preview

If that is not the case then open a new issue with a more detailed explanation for the thumbnail playback issue that I am not able to reproduce.

**Closed by ParticleCore** 2017-08-03 20:41 UTC
Labels: duplicate

**Comment by NovaViper** [comment] 2017-08-03 21:23
@ParticleCore Ah, I didn't realize that YT had thumbnail previews by default, the thumbnail video settings on Iridium are working just fine.

And turning on the ads did the trick to make the subtitles come back. I wonder why that's the case

**Comment by ParticleCore** [comment] 2017-08-04 07:17
It is a logic that I implemented recently that is not working as it should because YouTube is reusing a certain parameter to load ads, subtitles, etc all in the same place. Gotta make a check pass to make sure that this only disables ads and nothing else.
