### ISSUE TITLE
Disabled autoplay is not need in playlists

### ISSUE THREAD

**Issue by TokcDK** [ParticleCore/Iridium#213] opened 2017-10-10 08:12 UTC
It is also in the YT+. When autoplay is disabled it is also disabled in playlists. It would be good to add suboption like 'Disable autoplay' --> '...but allow autoplay for playlists'. Because disabled autoplay is not need in playlists. Before it addon I was using Youtube center but it have no more updates and there is was it feature and it was very convenient.

**Comment by ParticleCore** [comment] 2017-10-10 08:19
Duplicate of https://github.com/ParticleCore/Iridium/issues/191

**Closed by ParticleCore** 2017-10-10 08:19 UTC
Labels: duplicate
