### ISSUE TITLE
Stop playlists auto play

### ISSUE THREAD

**Issue by tete0148** [ParticleCore/Iridium#135] opened 2017-09-03 21:23 UTC
Is it possible to disable YouTube playlists auto play ? It's to annoying when my watch later videos switch while I'm reading comments... 

Thanks :)

**Comment by ParticleCore** [comment] 2017-09-03 21:24
Duplicate of https://github.com/ParticleCore/Iridium/issues/78

**Closed by ParticleCore** 2017-09-03 21:24 UTC
Labels: duplicate
