### ISSUE TITLE
Reverse Playlist button is gone.

### ISSUE THREAD

**Issue by Mathew322** [ParticleCore/Iridium#707] opened 2019-04-13 04:53 UTC
**Browser Name:** Mozilla Firefox
**Browser Version:** 67.0b10 (64-bit)
**Operating System:** Windows 7 Ultimate
**Software Type:** Add-on
**Software Version:** 0.2.5
**Problem Description:** The Reverse Playlist button is just gone from all playlists.
**Steps to reproduce:** It's just not there.

**Comment by spartanatreyu** [comment] 2019-04-15 02:27
**Browser Name:** Mozilla Firefox
**Browser Version:** 66.0.2 (64-bit) and 66.0.3 (64-bit)
**Operating System:** macOS 10.14.4 Mojave
**Software Type:** Add-on
**Software Version:** 0.2.5
**Problem Description:** The "Loop playlist", "Shuffle playlist", "Reverse playlist" and "Save playlist" buttons are all missing and have been replaced with a different button. The new button displays 3 vertical dots. I believe it's supposed to open a dropdown menu but clicking it only starts the google material design ripple effect and no menu appears. Hovering over the button displays no tooltip. Here is the rendered markup of the toolbar that is meant to contain the four buttons listed above:

```html
<div id="playlist-actions" class="style-scope ytd-playlist-panel-renderer"><ytd-menu-renderer class="yt-playlist-buttons style-scope ytd-playlist-panel-renderer">
    
    <div id="top-level-buttons" class="style-scope ytd-menu-renderer"></div>
    <yt-icon-button id="button" class="dropdown-trigger style-scope ytd-menu-renderer"><button id="button" class="style-scope yt-icon-button">
      <yt-icon class="style-scope ytd-menu-renderer"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon">
        <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" class="style-scope yt-icon"></path>
      </g></svg>
    
    
  </yt-icon>
    </button><paper-ripple class="style-scope yt-icon-button circle"><!--css-build:shady-->

    <div id="background" class="style-scope paper-ripple" style="opacity: 0.0068;"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
</paper-ripple></yt-icon-button>
  </ytd-menu-renderer><div id="save-button-wrapper" class="style-scope ytd-playlist-panel-renderer"><ytd-toggle-button-renderer class="style-scope ytd-playlist-panel-renderer" button-renderer=""></ytd-toggle-button-renderer></div><div id="overflow-menu" class="style-scope ytd-playlist-panel-renderer"></div></div>

 
```

Curiously enough, the buttons appear correctly when opening the same page in a private window. Here is the markup from the private window:

```html
<div id="playlist-actions" class="style-scope ytd-playlist-panel-renderer"><ytd-menu-renderer class="yt-playlist-buttons style-scope ytd-playlist-panel-renderer">
    
    <div id="top-level-buttons" class="style-scope ytd-menu-renderer"><ytd-toggle-button-renderer button-renderer="" class="style-scope ytd-menu-renderer style-grey-text size-default" is-icon-button="" has-no-text=""><a class="yt-simple-endpoint style-scope ytd-toggle-button-renderer" tabindex="-1"><yt-icon-button id="button" class="style-scope ytd-toggle-button-renderer style-grey-text size-default"><button id="button" class="style-scope yt-icon-button" aria-label="Loop playlist"><yt-icon class="style-scope ytd-toggle-button-renderer"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon">
        <path d="M7 7h10v3l4-4-4-4v3H5v6h2V7zm10 10H7v-3l-4 4 4 4v-3h12v-6h-2v4z" class="style-scope yt-icon"></path>
      </g></svg>
    
    
  </yt-icon></button></yt-icon-button><paper-tooltip role="tooltip" tabindex="-1" class="style-scope ytd-toggle-button-renderer" style="inset: 910px auto auto 837.408px;">
    

    <div id="tooltip" class="style-scope paper-tooltip hidden">
      Loop playlist
    </div>
  </paper-tooltip></a></ytd-toggle-button-renderer><ytd-toggle-button-renderer button-renderer="" class="style-scope ytd-menu-renderer style-grey-text size-default" is-icon-button="" has-no-text=""><a class="yt-simple-endpoint style-scope ytd-toggle-button-renderer" tabindex="-1"><yt-icon-button id="button" class="style-scope ytd-toggle-button-renderer style-grey-text size-default"><button id="button" class="style-scope yt-icon-button" aria-label="Shuffle playlist"><yt-icon class="style-scope ytd-toggle-button-renderer"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon">
        <path d="M10.59 9.17L5.41 4 4 5.41l5.17 5.17 1.42-1.41zM14.5 4l2.04 2.04L4 18.59 5.41 20 17.96 7.46 20 9.5V4h-5.5zm.33 9.41l-1.41 1.41 3.13 3.13L14.5 20H20v-5.5l-2.04 2.04-3.13-3.13z" class="style-scope yt-icon"></path>
      </g></svg>
    
    
  </yt-icon></button></yt-icon-button><paper-tooltip role="tooltip" tabindex="-1" class="style-scope ytd-toggle-button-renderer" style="inset: 910px auto auto 879.958px;">
    

    <div id="tooltip" class="style-scope paper-tooltip hidden">
      Shuffle playlist
    </div>
  </paper-tooltip></a></ytd-toggle-button-renderer><ytd-toggle-button-renderer button-renderer="" class="style-scope ytd-menu-renderer style-grey-text size-default" is-icon-button="" has-no-text=""><a class="yt-simple-endpoint style-scope ytd-toggle-button-renderer" tabindex="-1"><yt-icon-button id="button" class="style-scope ytd-toggle-button-renderer style-grey-text size-default"><button id="button" class="style-scope yt-icon-button" aria-label="Reverse playlist"><yt-icon class="style-scope ytd-toggle-button-renderer"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon">
        <path d="M6 21l-4-4h3V5h2v12h3L6 21z M19 7v12h-2V7h-3l4-4l4 4H19z" class="style-scope yt-icon"></path>
      </g></svg>
    
    
  </yt-icon></button></yt-icon-button><paper-tooltip role="tooltip" tabindex="-1" class="style-scope ytd-toggle-button-renderer" style="inset: 910px auto auto 925.033px;">
    

    <div id="tooltip" class="style-scope paper-tooltip hidden">
      Reverse playlist
    </div>
  </paper-tooltip></a></ytd-toggle-button-renderer></div>
    <yt-icon-button id="button" class="dropdown-trigger style-scope ytd-menu-renderer" hidden=""><button id="button" class="style-scope yt-icon-button">
      <yt-icon class="style-scope ytd-menu-renderer"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon">
        <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" class="style-scope yt-icon"></path>
      </g></svg>
    
    
  </yt-icon>
    </button></yt-icon-button>
  </ytd-menu-renderer><div id="save-button-wrapper" class="style-scope ytd-playlist-panel-renderer"><ytd-toggle-button-renderer class="style-scope ytd-playlist-panel-renderer style-grey-text size-default" button-renderer="" is-icon-button="" has-no-text=""><a class="yt-simple-endpoint style-scope ytd-toggle-button-renderer" tabindex="-1"><yt-icon-button id="button" class="style-scope ytd-toggle-button-renderer style-grey-text size-default"><button id="button" class="style-scope yt-icon-button" aria-label="Save playlist"><yt-icon class="style-scope ytd-toggle-button-renderer"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon">
        <path d="M14 10H2v2h12v-2zm0-4H2v2h12V6zm4 8v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zM2 16h8v-2H2v2z" class="style-scope yt-icon"></path>
      </g></svg>
    
    
  </yt-icon></button></yt-icon-button><paper-tooltip role="tooltip" tabindex="-1" class="style-scope ytd-toggle-button-renderer" style="inset: 910px auto auto 1168.08px;">
    

    <div id="tooltip" class="style-scope paper-tooltip hidden">
      Save playlist
    </div>
  </paper-tooltip></a></ytd-toggle-button-renderer></div><div id="overflow-menu" class="style-scope ytd-playlist-panel-renderer"></div></div>
```

Disabling the addon correctly returns the playlist buttons to their original state. The problem reappears after re-enabling the addon

**Comment by Mathew322** [comment] 2019-04-15 06:24
Oh wow I didn't even notice those buttons were missing too.

**Comment by spartanatreyu** [comment] 2019-04-15 23:13
At least it still works in private mode so I can still listen to my music, podcasts and shows in the right order

**Comment by Mathew322** [comment] 2019-04-15 23:42
Private mode? you mean the add-on works in private windows?

**Comment by spartanatreyu** [comment] 2019-04-16 02:26
yep

**Comment by Mathew322** [comment] 2019-04-16 03:35
What I'd figured out is that if I'm logged out of YouTube on a Private Window then the Plugin works like it should, if I log in however is breaks which is annoying cause is means I can't use YouTube Premium on my account.

**Comment by Freelancer95** [comment] 2019-04-17 01:02
Same issue, same browser. Please help *sobs*

**Comment by Schazmen** [comment] 2019-04-23 17:51
Same issue for me on FireFox. Started just today, though.

**Comment by Mathew322** [comment] 2019-04-23 20:26
Are you on the firefox beta channel? That's what I'm on, might explain the delay.

**Comment by charlificate** [comment] 2019-04-23 20:34
Yes please address this :/ This has been bothering me for months

**Comment by spartanatreyu** [comment] 2019-04-24 00:26
It probably won't be fixed right now.

The main developer is on hold due to health issues: https://github.com/ParticleCore/Iridium/issues/673

**Comment by Quizicalgin** [comment] 2019-04-24 07:54
Browser Name: Mozilla Firefox
Browser Version: 66.0.3 (64-bit) 
Operating System: Win 10 pro
Software Type: Add-on
Software Version: 0.2.5
Problem Description: instead of the three buttons it's a singular button with vertical dots.
Steps to reproduce: Just have it installed. Disable and reload it goes back to normal, but re-enable and it's the button of doom again. Autoplay has some jankiness too where it won't work.

For me it doesn't matter what window I open it in, it still has the useless three dot button. It only just started effecting my browser a few days ago and I used to could just refresh the page and it'd be fine, only that now no longer works. It's also sadly not my only issue, since the automatic play function of the playlist no longer works either depending on the playlist even with the "turning on autoplay in iridium's settings" work around. I wonder what youtube changed to make such a conflict. o3o I guess until it get's fixed I'll have to disable the add-on, since I don't think there's a keyboard control for making a playlist loop... ; x ;

Hopefully the dev feels better soon, health issues suck whatever they may be. x.x;

**Comment by Schazmen** [comment] 2019-04-25 08:54
Don't know if it's for everyone else, but the issue is fixed for me now. I did nothing, it's just back.

**Comment by Mathew322** [comment] 2019-04-25 12:07
Oh hey it looks like it's working again for me too!

**Comment by Quizicalgin** [comment] 2019-04-26 18:20
Huzzah!

**Comment by TheRangor** [comment] 2019-04-30 21:57
The problem seems to be intermittent. I was fine for the past 4-5 days, but today it's reappeared.

**Comment by dvdhngs** [comment] 2019-05-02 09:11
for me it's not showing yet.

**Comment by rnnc** [comment] 2019-05-03 12:25
problem reappeared

**Comment by XEntombmentX** [comment] 2019-05-04 08:56
I had this issue, so I planned on reinstalling it to see that would fix it. Now I can't install it at all. Going through the addon store says that I need to check my connection and installing from file says that the addon is corrupt.

**Comment by Mathew322** [comment] 2019-05-05 01:29
Okay so to make sure everyone is on the same page let me explain what happened. A certificate expired on Firefox when it shouldn't have done so which made a huge number of add-ons no longer work, this is why your add-ons might have been disabled at some point yesterday, this seems to be fixed now and all add-ons should be working again.

As far as Iridium not working again, I'm also experiencing this issue with playlists again as of today and not even going into a private window seems to fix it.

**Comment by Sebron** [comment] 2019-05-05 02:42
Issue has cropped up on Chrome now also
**Browser** Google Chrome
**Version** 74.0.3729.131 (Official Build) (64-bit)

**Comment by furiifuu** [comment] 2019-05-05 11:31
Experiencing the same issue on the latest version of Firefox. The button comprised of 3 dots is not functional. Any other option has disappeared for a while now. Nothing seems to fix it.

**Comment by milklineep** [comment] 2019-05-14 19:06
I thought some images might help.

Without Iridium:
![image](https://user-images.githubusercontent.com/28508187/57724777-1e205080-767b-11e9-9734-9ff664ec23d5.png)

With Iridium:
![image](https://user-images.githubusercontent.com/28508187/57724881-4ad46800-767b-11e9-90cb-671b0318c955.png)

Take care!

**Comment by Ebuall** [comment] 2019-06-02 18:07
Seems like a typical `this` error

**Comment by XEntombmentX** [comment] 2019-06-02 23:07
Firefox had rolled out some fixes for their addons a few weeks ago and it worked for a few days, but it’s back to not working. Hopefully it gets figured out soon.

**Comment by Ebuall** [comment] 2019-06-03 12:42
Even ignoring Firefox, it doesn't work in Chrome. There is an error in the code https://github.com/ParticleCore/Iridium/issues/715#issuecomment-497924442

**Comment by bskyb-backport** [comment] 2019-06-11 23:31
Google Chrome developers revealed their plans to deprecate a lot of old browser features and youtube developers are testing new versions of Polymer to support future Google Chrome versions. Sometimes youtube gets completely broken and empty even when all addons are disabled. I guess youtube uses random people as guineapig Q&A testers. As far as Iridium is concerned it is working fine when i force youtube to use older versions of Polymer and playlist reverse worked marvelously even on a monster 6790 video playlist

**Comment by spartanatreyu** [comment] 2019-06-12 05:04
Google does trial new changes to a small portion of the public at a time before rolling out those changes to everyone so anything can break at any time but a refresh will always revert you back to normal.

**Comment by Mathew322** [comment] 2019-06-12 05:21
You mean refresh as in CTRL+F5?

**Comment by bskyb-backport** [comment] 2019-06-12 16:06
sometimes deleting youtube cookies can opt you out current youtube experiment some cookies are set up to self destruct after some time. In the old days people copied new youtube cookies from each other to have new youtube website looks but nowadays youtube experiments are useless and outright  destructive. If you dig inside youtube back end code you literally find destructive code named "Destructive". Google is waging war on the public

**Comment by MIKEDADBABCLOCK** [comment] 2019-07-01 21:05
So is this issue fixed or nah? Cause this feature is the only thing I need this extension for

**Comment by Mathew322** [comment] 2019-07-01 22:20
It's not fixed for me, I think it's just broken.

**Comment by bskyb-backport** [comment] 2019-07-08 12:08
it was working on older version of youtube polymer 1.09212442 i could enable old polymer with fake user agent extension that  told youtube i used old browser but now youtube is forcing polymer 3.2.0 even on old browsers and Iridium is not working with polymer 3.2.0

**Comment by Mathew322** [comment] 2019-07-08 15:08
Looks like we'll just have to wait till Particle returns and updates it. :\

**Comment by Bwadcodit** [comment] 2019-07-10 14:08
For anyone looking for a fix and ending up here, I may have a workaround.

From the original Iridium script, I have isolated a piece of code that is autonomous and do actually reverse a Youtube playlist order. You can execute this in the developer tool console for instance (works for me in Firefox).

Note that the content of this code is solely copy-pasted from the original Iridium script.

```
(function () {

    iridium_api = {
        getSingleObjectByKey: function (obj, keys, match) {

            var i;
            var hasKey;
            var result;
            var property;

            for (property in obj) {

                if (obj.hasOwnProperty(property) && obj[property] !== null) {

                    hasKey = keys.constructor.name === "String" ? keys === property : keys.indexOf(property) > -1;

                    if (hasKey && (!match || obj[property].constructor.name !== "Object" && match(obj[property], obj))) {
                        return obj[property];
                    } else if (obj[property].constructor.name === "Object") {
                        if (result = this.getSingleObjectByKey(obj[property], keys, match)) {
                            return result;
                        }
                    } else if (obj[property].constructor.name === "Array") {
                        for (i = 0; i < obj[property].length; i++) {
                            if (result = this.getSingleObjectByKey(obj[property][i], keys, match)) {
                                return result;
                            }
                        }
                    }

                }

            }

        }
    };
    

    var i;
    var autoplay;
    var playlist;
    var ytd_watch;
    var yt_navigation_manager;
    var twoColumnWatchNextResults;

    if (ytd_watch = document.querySelector("ytd-watch, ytd-watch-flexy")) {
        if (ytd_watch.data) {
            if (twoColumnWatchNextResults = iridium_api.getSingleObjectByKey(ytd_watch.data, ["twoColumnWatchNextResults"])) {
                if ("playlist" in twoColumnWatchNextResults && "playlist" in (playlist = twoColumnWatchNextResults["playlist"])) {
                    if ("contents" in (playlist = playlist["playlist"])) {

                        playlist["contents"].reverse();

                        if ("currentIndex" in playlist) {
                            playlist["currentIndex"] = playlist["totalVideos"] - playlist["currentIndex"] - 1;
                        }

                        if ("localCurrentIndex" in playlist) {
                            playlist["localCurrentIndex"] = playlist["contents"].length - playlist["localCurrentIndex"] - 1;
                        }

                        if ("autoplay" in twoColumnWatchNextResults && "autoplay" in (autoplay = twoColumnWatchNextResults["autoplay"])) {
                            if ("sets" in (autoplay = autoplay["autoplay"])) {
                                for (i = 0; i < autoplay["sets"].length; i++) {
                                    if (autoplay["sets"][i]["previousButtonVideo"] && autoplay["sets"][i]["nextButtonVideo"]) {

                                        autoplay["sets"][i]["autoplayVideo"]       = autoplay["sets"][i]["previousButtonVideo"];
                                        autoplay["sets"][i]["previousButtonVideo"] = autoplay["sets"][i]["nextButtonVideo"];
                                        autoplay["sets"][i]["nextButtonVideo"]     = autoplay["sets"][i]["autoplayVideo"];

                                    }
                                }
                            }
                        }

                        if ("updatePageData_" in ytd_watch) {
                            ytd_watch["updatePageData_"](JSON.parse(JSON.stringify(ytd_watch.data)));
                        }

                        // timeout temporary workaround for playlist buttons ui not updating after first video changes
                        window.setTimeout(function () {
                            if (yt_navigation_manager = document.querySelector("yt-navigation-manager")) {
                                if ("updatePlayerComponents_" in yt_navigation_manager) {
                                    yt_navigation_manager["updatePlayerComponents_"](null, autoplay, null, playlist);
                                }
                            }
                        }, 500);

                    }
                }
            }
        }
    }

}());
```

**Comment by Bananasaurus** [comment] 2019-07-18 02:05
Mine was working just yesterday, and now it's not. I mean it's been on and off ever since I even added the plugin, but it usually fixed itself after a refresh, or browser-close, or a computer restart. Not this time.
Also, 

- Large playlists like the Game Grumps, in attempting to play from the beginning, I was unable to. It would just start the playlist at around 150 videos back. I had to manually change the number in the URL, and then the "reverse" option completely broke for that... but not other playlists.
- Oddly, before this, I had watched the entirety of Jacksepticeye's videos, and he has even MORE than the Game Grumps. It worked perfectly fine, starting from his very first, objectively awkward video. 😜

**Comment by hydargos123** [comment] 2019-07-22 14:52
I haven't found any other extension, website, script or anything to reverse a playlist order. Iridium was the only one and now it's gone. It's very annoying to not be able to watch all the videos of a channel in the right order or having to press multiple time the previous button before it switch to the next videos instead of just sitting and watching... :(

**Comment by bskyb-backport** [comment] 2019-07-28 07:42
as a crude fix you can try jamming the PageDown button with a toothpick or a mouse on the channel Uploads page until all videos load then Ctrl+S to save the page as a text file then import all the urls into a desktop player

**Comment by AceAttorneyMaster111** [comment] 2019-10-06 21:56
Is this fixed in version 1?

**Comment by ParticleCore** [comment] 2019-10-06 21:57
@AceAttorneyMaster111 I'm afraid not, I haven't been able to re-develop this feature yet, but I plan to. For the moment it will remain as is

Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0

**Closed by ParticleCore** 2019-10-06 21:57 UTC

**Comment by gappleto97** [comment] 2019-10-24 21:11
@ParticleCore, would you be willing to keep this open since you plan to re-implement it? That would make it easier to track when this feature is done, instead of just checking the release list every so often.

Totally get it if the answer is no, but it would be nice.

**Comment by AceAttorneyMaster111** [comment] 2019-10-24 22:11
I'm not sure if this issue is the right place to do that since it had to do with a previous version, but you can make a new issue framed as a feature request if you want. (disclaimer: i'm not particlecore, not sure where they want to take the project)

**Comment by lkamal** [comment] 2020-01-25 08:33
Please keep this open or create a new one for a new feature.
