### ISSUE TITLE
Mini player issue

### ISSUE THREAD

**Issue by rehannali** [ParticleCore/Iridium#609] opened 2018-11-06 19:12 UTC
Hi, after convert to the mini player when I press close button to close mini player it didn't close it. It only hides it. After the refresh of page mini player still persist. 

I'm using the latest version of chrome extension and user script.

**Comment by ParticleCore** [comment] 2018-11-06 19:17
Duplicate of #575

**Closed by ParticleCore** 2018-11-06 19:17 UTC
Labels: duplicate
