### ISSUE TITLE
Feature request: Control autoplay in playlists

### ISSUE THREAD

**Issue by Konahrik13** [ParticleCore/Iridium#461] opened 2018-05-21 03:17 UTC
As it is (or it is in Iridium already and I simply don't know how to do it) you can't listen to just one video in a playlist, as soon as it ends to goes to the next. It's quite irritating, which is why I'm asking if it's possible to implement a on/off autoplay control or something so that can be done.

**Comment by ParticleCore** [comment] 2018-05-21 11:32
Duplicate of #78

**Closed by ParticleCore** 2018-05-21 11:32 UTC
Labels: duplicate
