### ISSUE TITLE
Iridium 1.2.4 causes encoding errors on Firefox Nightly 72.0a1 

### ISSUE THREAD

**Issue by the-nothingman** [ParticleCore/Iridium#792] opened 2019-10-30 00:32 UTC
Just like the title says when using the addon in Firefox nightly (72.0a1) it causes "Content Encoding Error" that break youtube causing it to fail at loading

**Comment by ParticleCore** [comment] 2019-10-30 00:51
Duplicate of #788

**Closed by ParticleCore** 2019-10-30 00:51 UTC
Labels: duplicate
