### ISSUE TITLE
Added Watched to videos that a persons has already viewed.

### ISSUE THREAD

**Issue by mkruer** [ParticleCore/Iridium#647] opened 2018-12-30 19:31 UTC
YouTubeCenter by YePpHa https://github.com/YePpHa/YouTubeCenter had a very useful feature a 
“Watched” overlay on all videos that a persons has already viewed.

https://github.com/YePpHa/YouTubeCenter/wiki/Features#Watched_Videos 

Please consider for future implementation

**Comment by ParticleCore** [comment] 2018-12-30 19:33
Duplicate of #233

**Closed by ParticleCore** 2018-12-30 19:33 UTC
Labels: duplicate
