### ISSUE TITLE
[Feature] Default video quality for embedded videos

### ISSUE THREAD

**Issue by mozkan007** [ParticleCore/Iridium#397] opened 2018-03-20 05:41 UTC
Hi,

The default video quality option is a great feature but it works only on youtube.com. However, when I open an embedded video on any site, I can not use this option anymore.  Can you provide additionally this option works for embedded videos? Thanks.

**Comment by ParticleCore** [comment] 2018-03-20 08:01
Duplicate of #267

**Closed by ParticleCore** 2018-03-20 08:01 UTC
Labels: duplicate
