### ISSUE TITLE
Request: Static Header

### ISSUE THREAD

**Issue by rayman89** [ParticleCore/Iridium#368] opened 2018-02-26 22:30 UTC
Could you add an option to make the youtube header static?

**Comment by ParticleCore** [comment] 2018-02-26 22:42
Duplicate of #277

Please do not open duplicate issues on purpose.

**Closed by ParticleCore** 2018-02-26 22:42 UTC
Labels: duplicate

**Comment by rayman89** [comment] 2018-02-27 17:31
You closed it so I thought you forgot about it or something sorry.

**Comment by ParticleCore** [comment] 2018-02-27 17:54
>#### Feature request:
> - There is currently no intention to accept feature requests, but they can be requested nonetheless for future consideration
> - Feature requests will be automatically closed and labeled as "Feature" for easier access and better organization

https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md
