### ISSUE TITLE
[Feature] Allow resizing of the minimised-scrolling video player

### ISSUE THREAD

**Issue by Spudnik1** [ParticleCore/Iridium#454] opened 2018-05-15 21:05 UTC
It is currently only possible to move the scrolling player around, but not resize it. Being able to resize the player would be useful to see small text in the video while scrolling in the comments.
![Scrolling Player](https://user-images.githubusercontent.com/31168189/40083350-c2aa5baa-588b-11e8-95e8-5be3211b98c7.PNG)

**Comment by ParticleCore** [comment] 2018-05-15 21:08
Duplicate of #360

**Closed by ParticleCore** 2018-05-15 21:08 UTC
Labels: duplicate
